#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
US Tech Stock - 深度回測腳本 (Dynamic Trailing Stop)
================================================================================
針對 PLTR, NVDA, TSLA, NFLX 進行深度回測。

回測設定:
- 期間: 2017-10-16 ~ 2023-10-15
- 初始資金: $1,000,000
- 信心度門檻: > 90%
- 基準: ^IXIC Buy & Hold

風險管理機制:
- 硬性停損 (Hard Stop): -8%
- 移動停利啟動門檻: +15%
- 動態回檔停利:
  - 一般區 (15-25%): 回檔 8% 出場
  - 高獲利區 (>25%): 回檔 11% 出場

作者：Phil Liang (Generated by Gemini)
日期：2026-01-18
================================================================================
"""

import os
import sys
import json
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from tqdm import tqdm

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

from train_us_tech_buy_agent import (
    load_or_update_local_csv,
    calculate_features,
    BENCHMARK, FEATURE_COLS, VAL_RANGE, MODELS_PATH
)

from stable_baselines3 import PPO


# =============================================================================
# 回測參數
# =============================================================================
TARGET_TICKERS = ["PLTR", "NVDA", "TSLA", "NFLX"]
VAL_START, VAL_END = VAL_RANGE
INITIAL_CAPITAL = 1_000_000

# 進場條件
CONFIDENCE_THRESHOLD = 0.90

# 風險管理參數
HARD_STOP_PCT = -0.08          # 硬性停損 -8%
TRAILING_ACTIVATION = 0.15     # 移動停利啟動 +15%
HIGH_PROFIT_THR = 0.25         # 高獲利區門檻 +25%
CALLBACK_BASE = 0.08           # 一般區回檔容忍度 8%
CALLBACK_HIGH = 0.11           # 高獲利區回檔容忍度 11%

OUTPUT_DIR = "backtest_results"


# =============================================================================
# 模型載入
# =============================================================================
def load_model_manifest(models_path: str) -> dict:
    manifest_path = os.path.join(models_path, "model_manifest.json")
    if not os.path.exists(manifest_path):
        return None
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_ticker_model(ticker: str, manifest: dict) -> PPO:
    if ticker not in manifest.get("tickers", {}):
        return None
    model_path = manifest["tickers"][ticker]["model_path"]
    if not os.path.exists(model_path):
        return None
    return PPO.load(model_path, device="cpu")


def get_action_confidence(model: PPO, obs: np.ndarray) -> tuple:
    obs_tensor = torch.as_tensor(obs.reshape(1, -1), dtype=torch.float32)
    with torch.no_grad():
        distribution = model.policy.get_distribution(obs_tensor)
        probs = distribution.distribution.probs.numpy()[0]
        action, _ = model.predict(obs, deterministic=True)
        return int(action), float(probs[1])


# =============================================================================
# 回測引擎
# =============================================================================
class DynamicTrailingBacktester:
    """動態回檔停利回測器"""
    
    def __init__(self, initial_capital: float = INITIAL_CAPITAL):
        self.initial_capital = initial_capital
        self.trades = []
        self.equity_curve = []
        self.buy_signals = []
        self.sell_signals = []  # (date, price, reason)
    
    def run(self, ticker: str, model: PPO, features_df: pd.DataFrame) -> dict:
        """執行回測"""
        # 過濾測試期間
        test_df = features_df[
            (features_df.index >= pd.Timestamp(VAL_START)) &
            (features_df.index <= pd.Timestamp(VAL_END))
        ].copy()
        
        if len(test_df) == 0:
            return None
        
        capital = self.initial_capital
        position = None  # {'shares', 'buy_price', 'buy_date', 'buy_idx', 'highest_price'}
        
        dates = test_df.index.tolist()
        closes = test_df['Close'].values
        highs = test_df['High'].values
        lows = test_df['Low'].values
        features = test_df[FEATURE_COLS].values.astype(np.float32)
        
        for i in tqdm(range(len(test_df)), desc=f"  Backtesting {ticker}", leave=False):
            date = dates[i]
            price = closes[i]
            high = highs[i]
            low = lows[i]
            
            # 記錄淨值
            if position:
                current_value = capital + position['shares'] * price
            else:
                current_value = capital
            self.equity_curve.append({'date': date, 'value': current_value})
            
            # =====================================================================
            # 持有中：檢查出場條件
            # =====================================================================
            if position is not None:
                buy_price = position['buy_price']
                current_return = price / buy_price - 1
                highest_return = position['highest_price'] / buy_price - 1
                drawdown_from_high = (position['highest_price'] - price) / position['highest_price']
                
                # 更新最高價
                if price > position['highest_price']:
                    position['highest_price'] = price
                
                sell_reason = None
                
                # A. 硬性停損檢查 (-8%)
                if current_return <= HARD_STOP_PCT:
                    sell_reason = "Hard Stop"
                
                # B. 移動停利邏輯
                elif highest_return >= TRAILING_ACTIVATION:
                    # 判斷回檔容忍度
                    if highest_return >= HIGH_PROFIT_THR:
                        callback_limit = CALLBACK_HIGH
                    else:
                        callback_limit = CALLBACK_BASE
                    
                    if drawdown_from_high >= callback_limit:
                        sell_reason = f"Trailing Stop ({callback_limit:.0%})"
                
                # 執行賣出
                if sell_reason:
                    sell_value = position['shares'] * price
                    profit = sell_value - position['shares'] * buy_price
                    capital += sell_value
                    
                    self.trades.append({
                        'ticker': ticker,
                        'buy_date': position['buy_date'],
                        'buy_price': buy_price,
                        'sell_date': date,
                        'sell_price': price,
                        'return': current_return,
                        'profit': profit,
                        'hold_days': i - position['buy_idx'],
                        'exit_reason': sell_reason,
                        'max_return': highest_return
                    })
                    self.sell_signals.append((date, price, sell_reason))
                    position = None
            
            # =====================================================================
            # 空手：檢查進場條件
            # =====================================================================
            elif position is None:
                obs = features[i]
                action, confidence = get_action_confidence(model, obs)
                
                # 進場條件：Action=1 且 信心度 > 90%
                if action == 1 and confidence > CONFIDENCE_THRESHOLD:
                    invest_amount = capital * 0.95  # 使用 95% 資金
                    shares = int(invest_amount / price)
                    
                    if shares > 0:
                        cost = shares * price
                        capital -= cost
                        
                        position = {
                            'shares': shares,
                            'buy_price': price,
                            'buy_date': date,
                            'buy_idx': i,
                            'highest_price': price,
                            'confidence': confidence
                        }
                        self.buy_signals.append((date, price, confidence))
        
        # 強制平倉 (回測結束時)
        if position is not None:
            final_price = closes[-1]
            sell_value = position['shares'] * final_price
            profit = sell_value - position['shares'] * position['buy_price']
            capital += sell_value
            current_return = final_price / position['buy_price'] - 1
            
            self.trades.append({
                'ticker': ticker,
                'buy_date': position['buy_date'],
                'buy_price': position['buy_price'],
                'sell_date': dates[-1],
                'sell_price': final_price,
                'return': current_return,
                'profit': profit,
                'hold_days': len(test_df) - position['buy_idx'],
                'exit_reason': 'End of Test',
                'max_return': position['highest_price'] / position['buy_price'] - 1
            })
        
        return self._calculate_metrics(test_df, ticker)
    
    def _calculate_metrics(self, test_df: pd.DataFrame, ticker: str) -> dict:
        """計算績效指標"""
        if not self.equity_curve:
            return None
        
        equity_df = pd.DataFrame(self.equity_curve)
        equity_df['date'] = pd.to_datetime(equity_df['date'])
        equity_df.set_index('date', inplace=True)
        
        initial = self.initial_capital
        final = equity_df['value'].iloc[-1]
        total_return = (final - initial) / initial
        
        days = (equity_df.index[-1] - equity_df.index[0]).days
        years = days / 365.0
        cagr = (1 + total_return) ** (1 / years) - 1 if years > 0 else 0
        
        daily_returns = equity_df['value'].pct_change().dropna()
        if len(daily_returns) > 0 and daily_returns.std() > 0:
            sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
        else:
            sharpe = 0
        
        rolling_max = equity_df['value'].cummax()
        drawdown = (equity_df['value'] - rolling_max) / rolling_max
        max_drawdown = drawdown.min()
        
        if self.trades:
            wins = sum(1 for t in self.trades if t['return'] > 0)
            win_rate = wins / len(self.trades)
            avg_return = np.mean([t['return'] for t in self.trades])
            avg_hold_days = np.mean([t['hold_days'] for t in self.trades])
        else:
            win_rate = 0
            avg_return = 0
            avg_hold_days = 0
        
        return {
            'ticker': ticker,
            'initial_capital': initial,
            'final_value': final,
            'total_return': total_return,
            'cagr': cagr,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'avg_return': avg_return,
            'avg_hold_days': avg_hold_days,
            'equity_df': equity_df,
            'trades': self.trades,
            'test_start': test_df.index[0],
            'test_end': test_df.index[-1]
        }


# =============================================================================
# Nasdaq Benchmark
# =============================================================================
def calculate_benchmark(benchmark_df: pd.DataFrame) -> dict:
    """計算 Nasdaq Buy & Hold 績效"""
    test_df = benchmark_df[
        (benchmark_df.index >= pd.Timestamp(VAL_START)) &
        (benchmark_df.index <= pd.Timestamp(VAL_END))
    ]
    
    if len(test_df) == 0:
        return None
    
    initial_price = test_df['Close'].iloc[0]
    final_price = test_df['Close'].iloc[-1]
    total_return = (final_price - initial_price) / initial_price
    
    days = (test_df.index[-1] - test_df.index[0]).days
    years = days / 365.0
    cagr = (1 + total_return) ** (1 / years) - 1 if years > 0 else 0
    
    equity = test_df['Close'] / initial_price * INITIAL_CAPITAL
    rolling_max = equity.cummax()
    drawdown = (equity - rolling_max) / rolling_max
    max_drawdown = drawdown.min()
    
    daily_returns = test_df['Close'].pct_change().dropna()
    if len(daily_returns) > 0 and daily_returns.std() > 0:
        sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
    else:
        sharpe = 0
    
    return {
        'ticker': '^IXIC (Benchmark)',
        'total_return': total_return,
        'cagr': cagr,
        'sharpe_ratio': sharpe,
        'max_drawdown': max_drawdown,
        'equity': equity
    }


# =============================================================================
# 視覺化
# =============================================================================
def plot_equity_curves(all_results: list, benchmark: dict, output_dir: str):
    """繪製累積淨值曲線"""
    fig, ax = plt.subplots(figsize=(14, 8))
    
    # 繪製各股策略曲線
    colors = ['#E91E63', '#4CAF50', '#2196F3', '#FF9800']
    for i, r in enumerate(all_results):
        if r is None:
            continue
        equity = r['equity_df']['value']
        ax.plot(equity.index, equity.values, label=f"{r['ticker']} (Return: {r['total_return']:.1%})",
                linewidth=2, color=colors[i % len(colors)])
    
    # 繪製 Benchmark
    if benchmark:
        ax.plot(benchmark['equity'].index, benchmark['equity'].values, 
                label=f"^IXIC B&H ({benchmark['total_return']:.1%})",
                linewidth=2, linestyle='--', color='gray', alpha=0.7)
    
    ax.axhline(y=INITIAL_CAPITAL, color='black', linestyle=':', alpha=0.5, label='Initial Capital')
    
    ax.set_title(f'累積淨值曲線 (Confidence > {CONFIDENCE_THRESHOLD:.0%})\n{VAL_START} ~ {VAL_END}', fontsize=14)
    ax.set_xlabel('Date', fontsize=11)
    ax.set_ylabel('Portfolio Value ($)', fontsize=11)
    ax.legend(loc='upper left', fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(bottom=0)
    
    plt.tight_layout()
    chart_path = os.path.join(output_dir, "equity_curves.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"✅ 淨值曲線已儲存: {chart_path}")


def plot_trade_signals(ticker: str, features_df: pd.DataFrame, 
                       backtester: DynamicTrailingBacktester, output_dir: str):
    """繪製交易訊號圖"""
    test_df = features_df[
        (features_df.index >= pd.Timestamp(VAL_START)) &
        (features_df.index <= pd.Timestamp(VAL_END))
    ]
    
    if len(test_df) == 0:
        return
    
    fig, ax = plt.subplots(figsize=(14, 6))
    
    ax.plot(test_df.index, test_df['Close'], label=f'{ticker} Close', color='black', linewidth=1)
    
    # 買入訊號
    if backtester.buy_signals:
        buy_dates, buy_prices, _ = zip(*backtester.buy_signals)
        ax.scatter(buy_dates, buy_prices, marker='^', color='green', s=100, 
                   label='Buy Signal', zorder=5)
    
    # 賣出訊號 (依原因分色)
    hard_stops = [(d, p) for d, p, r in backtester.sell_signals if 'Hard' in r]
    trailing_stops = [(d, p) for d, p, r in backtester.sell_signals if 'Trailing' in r]
    
    if hard_stops:
        dates, prices = zip(*hard_stops)
        ax.scatter(dates, prices, marker='v', color='red', s=100, label='Hard Stop', zorder=5)
    
    if trailing_stops:
        dates, prices = zip(*trailing_stops)
        ax.scatter(dates, prices, marker='v', color='orange', s=100, label='Trailing Stop', zorder=5)
    
    ax.set_title(f'{ticker} 交易訊號 (Confidence > {CONFIDENCE_THRESHOLD:.0%})', fontsize=13)
    ax.set_xlabel('Date', fontsize=11)
    ax.set_ylabel('Price ($)', fontsize=11)
    ax.legend(loc='upper left', fontsize=9)
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    chart_path = os.path.join(output_dir, f"trade_signals_{ticker}.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()


# =============================================================================
# 結果輸出
# =============================================================================
def save_report(all_results: list, benchmark: dict, output_dir: str):
    """儲存回測報告"""
    report_data = []
    
    for r in all_results:
        if r is None:
            continue
        report_data.append({
            'Ticker': r['ticker'],
            '測試起始': r['test_start'].strftime('%Y-%m-%d'),
            '測試結束': r['test_end'].strftime('%Y-%m-%d'),
            '初始資金': f"${r['initial_capital']:,.0f}",
            '最終淨值': f"${r['final_value']:,.0f}",
            '總報酬率': f"{r['total_return']:.1%}",
            '年化報酬(CAGR)': f"{r['cagr']:.1%}",
            '夏普值': f"{r['sharpe_ratio']:.2f}",
            '最大回撤(MDD)': f"{r['max_drawdown']:.1%}",
            '交易次數': r['total_trades'],
            '勝率': f"{r['win_rate']:.1%}",
            '平均報酬': f"{r['avg_return']:.1%}",
            '平均持有天數': f"{r['avg_hold_days']:.1f}"
        })
    
    # 加入 Benchmark
    if benchmark:
        report_data.append({
            'Ticker': '^IXIC (Benchmark)',
            '測試起始': VAL_START,
            '測試結束': VAL_END,
            '初始資金': f"${INITIAL_CAPITAL:,.0f}",
            '最終淨值': f"${INITIAL_CAPITAL * (1 + benchmark['total_return']):,.0f}",
            '總報酬率': f"{benchmark['total_return']:.1%}",
            '年化報酬(CAGR)': f"{benchmark['cagr']:.1%}",
            '夏普值': f"{benchmark['sharpe_ratio']:.2f}",
            '最大回撤(MDD)': f"{benchmark['max_drawdown']:.1%}",
            '交易次數': 'N/A',
            '勝率': 'N/A',
            '平均報酬': 'N/A',
            '平均持有天數': 'N/A'
        })
    
    report_df = pd.DataFrame(report_data)
    csv_path = os.path.join(output_dir, "final_backtest_report.csv")
    report_df.to_csv(csv_path, index=False, encoding='utf-8-sig')
    print(f"✅ 回測報告已儲存: {csv_path}")
    
    return report_df


def print_summary(all_results: list, benchmark: dict):
    """印出回測摘要"""
    print("\n" + "=" * 100)
    print("📊 深度回測結果摘要")
    print(f"   期間: {VAL_START} ~ {VAL_END}")
    print(f"   信心度門檻: > {CONFIDENCE_THRESHOLD:.0%}")
    print(f"   停損: {HARD_STOP_PCT:.0%} | 停利啟動: +{TRAILING_ACTIVATION:.0%}")
    print("=" * 100)
    
    print(f"\n{'Ticker':>10} | {'總報酬':>10} | {'CAGR':>8} | {'Sharpe':>8} | {'MDD':>8} | {'交易':>6} | {'勝率':>6}")
    print("-" * 80)
    
    for r in all_results:
        if r is None:
            continue
        print(f"{r['ticker']:>10} | {r['total_return']:>9.1%} | {r['cagr']:>7.1%} | {r['sharpe_ratio']:>7.2f} | {r['max_drawdown']:>7.1%} | {r['total_trades']:>6} | {r['win_rate']:>5.1%}")
    
    print("-" * 80)
    
    if benchmark:
        print(f"{'^IXIC B&H':>10} | {benchmark['total_return']:>9.1%} | {benchmark['cagr']:>7.1%} | {benchmark['sharpe_ratio']:>7.2f} | {benchmark['max_drawdown']:>7.1%} | {'N/A':>6} | {'N/A':>6}")
    
    print("=" * 100)


# =============================================================================
# 主程式
# =============================================================================
def main():
    print("=" * 70)
    print("  US Tech Stock - 深度回測 (Dynamic Trailing Stop)")
    print(f"  期間: {VAL_START} ~ {VAL_END}")
    print(f"  標的: {', '.join(TARGET_TICKERS)}")
    print("=" * 70)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 載入 manifest
    print("\n[Step 1] 載入模型...")
    manifest = load_model_manifest(MODELS_PATH)
    if manifest is None:
        print("❌ 無法載入 manifest")
        return
    
    # 載入基準指數
    print("\n[Step 2] 載入基準指數...")
    benchmark_df = load_or_update_local_csv(BENCHMARK)
    if benchmark_df is None:
        print("❌ 無法載入基準指數")
        return
    
    benchmark = calculate_benchmark(benchmark_df)
    
    # 執行回測
    print("\n[Step 3] 執行回測...")
    all_results = []
    all_backtesters = {}
    all_features = {}
    
    for ticker in TARGET_TICKERS:
        print(f"\n📈 {ticker}")
        print("-" * 40)
        
        model = load_ticker_model(ticker, manifest)
        if model is None:
            print(f"  ⚠️ 模型載入失敗")
            all_results.append(None)
            continue
        print(f"  ✅ 模型載入成功")
        
        raw_df = load_or_update_local_csv(ticker)
        if raw_df is None:
            all_results.append(None)
            continue
        
        features_df = calculate_features(raw_df, benchmark_df, ticker, use_cache=True)
        all_features[ticker] = features_df
        
        backtester = DynamicTrailingBacktester(INITIAL_CAPITAL)
        result = backtester.run(ticker, model, features_df)
        all_results.append(result)
        all_backtesters[ticker] = backtester
        
        if result:
            print(f"  📊 Return: {result['total_return']:.1%} | Trades: {result['total_trades']} | Win: {result['win_rate']:.1%}")
    
    # 輸出結果
    print("\n[Step 4] 輸出結果...")
    
    print_summary(all_results, benchmark)
    save_report(all_results, benchmark, OUTPUT_DIR)
    plot_equity_curves(all_results, benchmark, OUTPUT_DIR)
    
    # 繪製個股交易訊號
    for ticker in TARGET_TICKERS:
        if ticker in all_backtesters and ticker in all_features:
            plot_trade_signals(ticker, all_features[ticker], all_backtesters[ticker], OUTPUT_DIR)
    
    print("\n" + "=" * 70)
    print("  ✅ 回測完成！")
    print(f"  📁 結果儲存於: {OUTPUT_DIR}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
