#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
NVDA 風險管理參數網格搜索
================================================================================
對 backtest_nvda_follow.py 的風險管理參數進行網格搜索，找出最佳組合。

測試參數：
- HARD_STOP_PCT: 硬性停損比例
- TRAILING_ACTIVATION: 移動停利啟動點
- CALLBACK_BASE: 基礎回檔止盈
- CALLBACK_HIGH: 高利潤回檔止盈

作者：Phil Liang (Generated by Gemini)
日期：2026-01-18
================================================================================
"""

import os
import sys
import json
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from tqdm import tqdm
import torch

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

from train_us_tech_buy_agent import (
    load_or_update_local_csv,
    calculate_features,
    BENCHMARK, FEATURE_COLS, MODELS_PATH
)

from stable_baselines3 import PPO

# 導入回測器
from backtest_nvda_follow import (
    TICKER, YEARLY_INJECTION, CONFIDENCE_HIGH, CONFIDENCE_LOW,
    BUY_RATIO_HIGH, BUY_RATIO_LOW,
    load_model_manifest, load_ticker_model, get_action_confidence,
    prepare_market_filter, check_entry_condition,
    calculate_nasdaq_benchmark
)


# =============================================================================
# 網格搜索參數範圍
# =============================================================================
GRID_PARAMS = {
    'HARD_STOP_PCT': [-0.08],
    'TRAILING_ACTIVATION': [0.20],
    'HIGH_PROFIT_THR': [0.25],
    'CALLBACK_BASE': [0.08],
    'CALLBACK_HIGH': [0.16,0.17, 0.18, 0.19]  # 密測 18% 周邊
}

# 回測日期範圍
BACKTEST_START = "2017-10-16"
BACKTEST_END = "2023-10-15"

OUTPUT_DIR = "grid_search_results_nvda"


# =============================================================================
# 修改版回測器 (接受參數)
# =============================================================================
class ParameterizedBacktester:
    """可接受參數的回測器"""
    
    def __init__(self, hard_stop: float, trailing_activation: float,
                 high_profit_thr: float, callback_base: float, callback_high: float,
                 yearly_injection: float = YEARLY_INJECTION):
        self.hard_stop_pct = hard_stop
        self.trailing_activation = trailing_activation
        self.high_profit_thr = high_profit_thr
        self.callback_base = callback_base
        self.callback_high = callback_high
        self.yearly_injection = yearly_injection
        
        self.capital_pool = 0.0
        self.positions = []
        self.trades = []
        self.equity_curve = []
        self.injection_log = []
    
    def run(self, model: PPO, features_df: pd.DataFrame, 
            benchmark_df: pd.DataFrame, start_date: str, end_date: str) -> dict:
        """執行回測"""
        test_df = prepare_market_filter(benchmark_df, features_df)
        test_df = test_df[
            (test_df.index >= pd.Timestamp(start_date)) &
            (test_df.index <= pd.Timestamp(end_date))
        ].copy()
        
        if len(test_df) == 0:
            return None
        
        dates = test_df.index.tolist()
        closes = test_df['Close'].values
        features = test_df[FEATURE_COLS].values.astype(np.float32)
        
        # 初始化
        self.capital_pool = self.yearly_injection
        self.injection_log.append({'date': dates[0], 'amount': self.yearly_injection})
        
        current_year = dates[0].year
        year_first_day_processed = {current_year: True}
        
        for i in range(len(test_df)):
            date = dates[i]
            price = closes[i]
            row = test_df.iloc[i]
            
            # 年度注入
            if date.year != current_year:
                current_year = date.year
                if current_year not in year_first_day_processed:
                    self.capital_pool += self.yearly_injection
                    self.injection_log.append({'date': date, 'amount': self.yearly_injection})
                    year_first_day_processed[current_year] = True
            
            # 計算淨值
            position_value = sum(p['shares'] * price for p in self.positions)
            current_value = self.capital_pool + position_value
            self.equity_curve.append({
                'date': date, 
                'value': current_value,
                'capital_pool': self.capital_pool,
                'position_value': position_value
            })
            
            # 出場檢查
            positions_to_remove = []
            for idx, pos in enumerate(self.positions):
                buy_price = pos['buy_price']
                current_return = price / buy_price - 1
                highest_return = pos['highest_price'] / buy_price - 1
                drawdown_from_high = (pos['highest_price'] - price) / pos['highest_price']
                
                if price > pos['highest_price']:
                    pos['highest_price'] = price
                
                sell_reason = None
                
                # 硬性停損
                if current_return <= self.hard_stop_pct:
                    sell_reason = "Hard Stop"
                # 移動停利
                elif highest_return >= self.trailing_activation:
                    cb_limit = self.callback_high if highest_return >= self.high_profit_thr else self.callback_base
                    if drawdown_from_high >= cb_limit:
                        sell_reason = "Trailing Stop"
                
                if sell_reason:
                    sell_value = pos['shares'] * price
                    profit = sell_value - pos['cost']
                    self.capital_pool += sell_value
                    
                    self.trades.append({
                        'buy_date': pos['buy_date'],
                        'buy_price': buy_price,
                        'sell_date': date,
                        'sell_price': price,
                        'return': current_return,
                        'profit': profit,
                        'hold_days': (date - pos['buy_date']).days,
                        'exit_reason': sell_reason
                    })
                    positions_to_remove.append(idx)
            
            for idx in sorted(positions_to_remove, reverse=True):
                self.positions.pop(idx)
            
            # 進場檢查
            obs = features[i]
            action, confidence = get_action_confidence(model, obs)
            
            if action == 1:
                allow_entry, entry_type = check_entry_condition(row)
                
                if allow_entry:
                    if confidence > CONFIDENCE_HIGH:
                        buy_ratio = BUY_RATIO_HIGH
                    elif confidence >= CONFIDENCE_LOW:
                        buy_ratio = BUY_RATIO_LOW
                    else:
                        buy_ratio = 0
                    
                    if buy_ratio > 0 and self.capital_pool > 0:
                        invest_amount = self.capital_pool * buy_ratio
                        
                        # 跳過無法買到1股的情況
                        if invest_amount < price:
                            continue
                        
                        shares = invest_amount / price
                        
                        if shares > 0:
                            cost = shares * price
                            self.capital_pool -= cost
                            
                            self.positions.append({
                                'shares': shares,
                                'buy_price': price,
                                'buy_date': date,
                                'cost': cost,
                                'highest_price': price
                            })
        
        return self._calculate_metrics(test_df)
    
    def _calculate_metrics(self, test_df: pd.DataFrame) -> dict:
        """計算績效指標"""
        if not self.equity_curve:
            return None
        
        equity_df = pd.DataFrame(self.equity_curve)
        equity_df['date'] = pd.to_datetime(equity_df['date'])
        equity_df.set_index('date', inplace=True)
        
        total_injected = sum(log['amount'] for log in self.injection_log)
        final_value = equity_df['value'].iloc[-1]
        total_return = (final_value - total_injected) / total_injected
        
        days = (equity_df.index[-1] - equity_df.index[0]).days
        years = days / 365.0
        cagr = (final_value / total_injected) ** (1 / years) - 1 if years > 0 else 0
        
        daily_returns = equity_df['value'].pct_change().dropna()
        if len(daily_returns) > 0 and daily_returns.std() > 0:
            sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
        else:
            sharpe = 0
        
        rolling_max = equity_df['value'].cummax()
        drawdown = (equity_df['value'] - rolling_max) / rolling_max
        max_drawdown = drawdown.min()
        
        if self.trades:
            wins = sum(1 for t in self.trades if t['return'] > 0)
            win_rate = wins / len(self.trades)
        else:
            win_rate = 0
        
        return {
            'total_injected': total_injected,
            'final_value': final_value,
            'total_return': total_return,
            'cagr': cagr,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'total_trades': len(self.trades),
            'win_rate': win_rate
        }


# =============================================================================
# 網格搜索執行
# =============================================================================
def run_grid_search(model, features_df, benchmark_df):
    """執行網格搜索"""
    # 生成所有參數組合
    param_names = list(GRID_PARAMS.keys())
    param_values = list(GRID_PARAMS.values())
    combinations = list(itertools.product(*param_values))
    
    print(f"\n總共測試 {len(combinations)} 組參數組合")
    print(f"預估時間: 約 {len(combinations) * 0.5:.0f} 分鐘\n")
    
    results = []
    
    for combo in tqdm(combinations, desc="Grid Search Progress"):
        params = dict(zip(param_names, combo))
        
        backtester = ParameterizedBacktester(
            hard_stop=params['HARD_STOP_PCT'],
            trailing_activation=params['TRAILING_ACTIVATION'],
            high_profit_thr=params['HIGH_PROFIT_THR'],
            callback_base=params['CALLBACK_BASE'],
            callback_high=params['CALLBACK_HIGH']
        )
        
        result = backtester.run(model, features_df, benchmark_df, 
                                BACKTEST_START, BACKTEST_END)
        
        if result:
            result.update(params)
            results.append(result)
    
    return pd.DataFrame(results)


# =============================================================================
# 結果分析與視覺化
# =============================================================================
def analyze_results(results_df: pd.DataFrame, output_dir: str):
    """分析並視覺化結果"""
    
    # 排序並儲存
    results_sorted = results_df.sort_values('sharpe_ratio', ascending=False)
    csv_path = os.path.join(output_dir, "grid_search_results.csv")
    results_sorted.to_csv(csv_path, index=False, encoding='utf-8-sig')
    print(f"✅ 結果已儲存: {csv_path}")
    
    # 顯示 Top 10
    print("\n" + "=" * 100)
    print("📊 Top 10 參數組合 (依 Sharpe Ratio 排序)")
    print("=" * 100)
    
    display_cols = ['HARD_STOP_PCT', 'TRAILING_ACTIVATION', 'HIGH_PROFIT_THR',
                    'CALLBACK_BASE', 'CALLBACK_HIGH', 'total_return', 'sharpe_ratio', 'max_drawdown', 'win_rate']
    
    top_10 = results_sorted[display_cols].head(10)
    
    for idx, row in top_10.iterrows():
        print(f"\nRank {top_10.index.get_loc(idx) + 1}:")
        print(f"  Hard Stop: {row['HARD_STOP_PCT']:.1%} | Trail Act: {row['TRAILING_ACTIVATION']:.1%} | High Profit: {row['HIGH_PROFIT_THR']:.1%}")
        print(f"  CB Base: {row['CALLBACK_BASE']:.1%} | CB High: {row['CALLBACK_HIGH']:.1%}")
        print(f"  → Return: {row['total_return']:.1%} | Sharpe: {row['sharpe_ratio']:.2f} | MDD: {row['max_drawdown']:.1%}")
    
    print("=" * 100)
    
    # 視覺化
    plot_heatmaps(results_df, output_dir)
    plot_parameter_impact(results_df, output_dir)
    plot_scatter_matrix(results_df, output_dir)


def plot_heatmaps(results_df: pd.DataFrame, output_dir: str):
    """繪製熱力圖 (2D 參數組合)"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    
    param_pairs = [
        ('HARD_STOP_PCT', 'TRAILING_ACTIVATION'),
        ('TRAILING_ACTIVATION', 'HIGH_PROFIT_THR'),
        ('HIGH_PROFIT_THR', 'CALLBACK_BASE'),
        ('HIGH_PROFIT_THR', 'CALLBACK_HIGH'),
        ('TRAILING_ACTIVATION', 'CALLBACK_BASE'),
        ('CALLBACK_BASE', 'CALLBACK_HIGH')
    ]
    
    for idx, (param1, param2) in enumerate(param_pairs):
        ax = axes[idx // 3, idx % 3]
        
        # 取該組合的平均 Sharpe
        pivot = results_df.groupby([param1, param2])['sharpe_ratio'].mean().unstack()
        
        sns.heatmap(pivot, annot=True, fmt='.2f', cmap='RdYlGn', ax=ax, 
                    cbar_kws={'label': 'Sharpe Ratio'})
        ax.set_title(f'{param1} vs {param2}')
        ax.set_xlabel(param2)
        ax.set_ylabel(param1)
    
    plt.tight_layout()
    heatmap_path = os.path.join(output_dir, "parameter_heatmaps.png")
    plt.savefig(heatmap_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"✅ 熱力圖已儲存: {heatmap_path}")


def plot_parameter_impact(results_df: pd.DataFrame, output_dir: str):
    """繪製單參數影響圖"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    
    params = ['HARD_STOP_PCT', 'TRAILING_ACTIVATION', 'HIGH_PROFIT_THR', 'CALLBACK_BASE', 'CALLBACK_HIGH']
    
    for idx, param in enumerate(params):
        ax = axes[idx // 3, idx % 3]
        
        grouped = results_df.groupby(param).agg({
            'sharpe_ratio': 'mean',
            'total_return': 'mean',
            'max_drawdown': 'mean'
        })
        
        ax2 = ax.twinx()
        
        grouped['sharpe_ratio'].plot(ax=ax, marker='o', color='blue', label='Sharpe', linewidth=2)
        grouped['total_return'].plot(ax=ax2, marker='s', color='green', label='Return', linewidth=2)
        
        ax.set_xlabel(param)
        ax.set_ylabel('Sharpe Ratio', color='blue')
        ax2.set_ylabel('Total Return', color='green')
        ax.tick_params(axis='y', labelcolor='blue')
        ax2.tick_params(axis='y', labelcolor='green')
        ax.set_title(f'{param} 影響分析')
        ax.grid(True, alpha=0.3)
        
        # 合併圖例
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, loc='upper left')
    
    plt.tight_layout()
    impact_path = os.path.join(output_dir, "parameter_impact.png")
    plt.savefig(impact_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"✅ 參數影響圖已儲存: {impact_path}")


def plot_scatter_matrix(results_df: pd.DataFrame, output_dir: str):
    """繪製散點矩陣 (Return vs Sharpe vs MDD)"""
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    
    # Sharpe vs Return
    ax1 = axes[0]
    scatter1 = ax1.scatter(results_df['sharpe_ratio'], results_df['total_return'],
                          c=results_df['max_drawdown'], cmap='RdYlGn_r', 
                          s=50, alpha=0.6)
    ax1.set_xlabel('Sharpe Ratio')
    ax1.set_ylabel('Total Return')
    ax1.set_title('Sharpe vs Return (色=MDD)')
    plt.colorbar(scatter1, ax=ax1, label='Max Drawdown')
    ax1.grid(True, alpha=0.3)
    
    # Sharpe vs MDD
    ax2 = axes[1]
    scatter2 = ax2.scatter(results_df['sharpe_ratio'], results_df['max_drawdown'],
                          c=results_df['total_return'], cmap='RdYlGn', 
                          s=50, alpha=0.6)
    ax2.set_xlabel('Sharpe Ratio')
    ax2.set_ylabel('Max Drawdown')
    ax2.set_title('Sharpe vs MDD (色=Return)')
    plt.colorbar(scatter2, ax=ax2, label='Total Return')
    ax2.grid(True, alpha=0.3)
    
    # Return vs MDD
    ax3 = axes[2]
    scatter3 = ax3.scatter(results_df['total_return'], results_df['max_drawdown'],
                          c=results_df['sharpe_ratio'], cmap='RdYlGn', 
                          s=50, alpha=0.6)
    ax3.set_xlabel('Total Return')
    ax3.set_ylabel('Max Drawdown')
    ax3.set_title('Return vs MDD (色=Sharpe)')
    plt.colorbar(scatter3, ax=ax3, label='Sharpe Ratio')
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    scatter_path = os.path.join(output_dir, "performance_scatter.png")
    plt.savefig(scatter_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"✅ 散點圖已儲存: {scatter_path}")


# =============================================================================
# 主程式
# =============================================================================
def main():
    print("=" * 70)
    print("  NVDA 風險管理參數網格搜索")
    print(f"  期間: {BACKTEST_START} ~ {BACKTEST_END}")
    print("=" * 70)
    print("\n測試參數範圍:")
    for param, values in GRID_PARAMS.items():
        print(f"  {param}: {values}")
    print("=" * 70)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 載入模型
    print("\n[Step 1] 載入模型...")
    manifest = load_model_manifest(MODELS_PATH)
    if manifest is None:
        print("❌ 無法載入 manifest")
        return
    
    model = load_ticker_model(TICKER, manifest)
    if model is None:
        print(f"❌ 無法載入 {TICKER} 模型")
        return
    print(f"✅ {TICKER} 模型載入成功")
    
    # 載入數據
    print("\n[Step 2] 載入數據...")
    benchmark_df = load_or_update_local_csv(BENCHMARK)
    if benchmark_df is None:
        print("❌ 無法載入基準指數")
        return
    
    raw_df = load_or_update_local_csv(TICKER)
    if raw_df is None:
        print(f"❌ 無法載入 {TICKER} 數據")
        return
    
    features_df = calculate_features(raw_df, benchmark_df, TICKER, use_cache=True)
    print(f"✅ 數據載入完成")
    
    # 執行網格搜索
    print("\n[Step 3] 執行網格搜索...")
    results_df = run_grid_search(model, features_df, benchmark_df)
    
    # 分析結果
    print("\n[Step 4] 分析結果...")
    analyze_results(results_df, OUTPUT_DIR)
    
    print("\n" + "=" * 70)
    print("  ✅ 網格搜索完成！")
    print(f"  📁 結果儲存於: {OUTPUT_DIR}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
