#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
US Tech Stock Buy Agent - 決策表現評估腳本
================================================================================
測試對象: NVDA, MSFT, AAPL, AMZN, META, AVGO, GOOGL, TSLA, NFLX, PLTR
測試期間: 2017-10-16 ~ 2023-10-15 (VAL_RANGE)

核心目的:
- 量化 Agent 的預測能力
- 與市場真實起漲點頻率進行對比

輸出:
- test_results_summary.csv: 各股統計指標
- test_results_chart.png: 決策成功率 vs 市場真實頻率對比圖

作者：Phil Liang (Generated by Gemini)
日期：2026-01-18
================================================================================
"""

import os
import sys
import json
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from tqdm import tqdm

# Windows 終端機 UTF-8 編碼設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# 設定中文字型
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# 導入訓練腳本中的函數
from train_us_tech_buy_agent import (
    load_or_update_local_csv,
    calculate_features,
    TICKERS, BENCHMARK, FEATURE_COLS, VAL_RANGE, MODELS_PATH
)

from stable_baselines3 import PPO


# =============================================================================
# 常量定義
# =============================================================================
VAL_START, VAL_END = VAL_RANGE
OUTPUT_DIR = "test_results"


# =============================================================================
# 模型載入
# =============================================================================
def load_model_manifest(models_path: str) -> dict:
    """載入 model_manifest.json"""
    manifest_path = os.path.join(models_path, "model_manifest.json")
    
    if not os.path.exists(manifest_path):
        print(f"❌ 找不到 model_manifest.json: {manifest_path}")
        return None
    
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_ticker_model(ticker: str, manifest: dict) -> PPO:
    """載入指定 Ticker 的模型"""
    if ticker not in manifest.get("tickers", {}):
        print(f"  ⚠️ {ticker} 不在 manifest 中")
        return None
    
    model_path = manifest["tickers"][ticker]["model_path"]
    
    if not os.path.exists(model_path):
        print(f"  ⚠️ {ticker} 模型檔案不存在: {model_path}")
        return None
    
    try:
        model = PPO.load(model_path, device="cpu")
        return model
    except Exception as e:
        print(f"  ❌ {ticker} 模型載入失敗: {e}")
        return None


# =============================================================================
# 決策評估
# =============================================================================
def get_action_confidence(model: PPO, obs: np.ndarray) -> tuple:
    """
    取得模型的動作與信心度
    
    Args:
        model: PPO 模型
        obs: 觀察值 (特徵向量)
    
    Returns:
        tuple: (action, buy_confidence)
            - action: 0 (WAIT) 或 1 (BUY)
            - buy_confidence: 買入動作的機率值
    """
    obs_tensor = torch.as_tensor(obs.reshape(1, -1), dtype=torch.float32)
    
    with torch.no_grad():
        # 取得動作分佈
        distribution = model.policy.get_distribution(obs_tensor)
        probs = distribution.distribution.probs.numpy()[0]
        
        # 取得動作
        action, _ = model.predict(obs, deterministic=True)
        action = int(action)
        
        # Buy 信心度 (Action 1 的機率)
        buy_confidence = float(probs[1])
    
    return action, buy_confidence


def evaluate_ticker(ticker: str, model: PPO, features_df: pd.DataFrame) -> dict:
    """
    評估單一股票的 Agent 表現
    
    Args:
        ticker: 股票代碼
        model: PPO 模型
        features_df: 包含特徵與目標的 DataFrame
    
    Returns:
        dict: 評估結果
    """
    # 過濾測試期間
    test_df = features_df[
        (features_df.index >= pd.Timestamp(VAL_START)) &
        (features_df.index <= pd.Timestamp(VAL_END))
    ].copy()
    
    if len(test_df) == 0:
        print(f"  ⚠️ {ticker} 在測試期間無資料")
        return None
    
    # 確保 Next_20d_Max 存在
    test_df = test_df.dropna(subset=['Next_20d_Max'])
    
    if len(test_df) == 0:
        print(f"  ⚠️ {ticker} 無有效目標標籤")
        return None
    
    print(f"  測試期間: {test_df.index[0].date()} ~ {test_df.index[-1].date()} ({len(test_df)} 天)")
    
    # 決策記錄
    decisions = []
    
    for idx in tqdm(range(len(test_df)), desc=f"  Evaluating {ticker}", leave=False):
        row = test_df.iloc[idx]
        date = test_df.index[idx]
        
        # 取得特徵
        obs = row[FEATURE_COLS].values.astype(np.float32)
        
        # 取得動作與信心度
        action, buy_confidence = get_action_confidence(model, obs)
        
        # 真實標籤
        next_20d_max = row['Next_20d_Max']
        is_rising_point = next_20d_max >= 0.10  # 市場真實起漲點
        
        decisions.append({
            'date': date,
            'action': action,
            'buy_confidence': buy_confidence,
            'next_20d_max': next_20d_max,
            'is_rising_point': is_rising_point,
            'is_buy': action == 1,
            'is_success': (action == 1) and is_rising_point  # True Positive
        })
    
    decisions_df = pd.DataFrame(decisions)
    
    # 計算統計指標
    total_days = len(decisions_df)
    rising_days = decisions_df['is_rising_point'].sum()
    trigger_count = decisions_df['is_buy'].sum()
    success_count = decisions_df['is_success'].sum()
    
    # 平均信心度 (僅計算買入決策)
    buy_decisions = decisions_df[decisions_df['is_buy']]
    avg_confidence = buy_decisions['buy_confidence'].mean() if len(buy_decisions) > 0 else 0.0
    
    # Precision & Recall
    precision = success_count / trigger_count if trigger_count > 0 else 0.0
    recall = success_count / rising_days if rising_days > 0 else 0.0
    
    # 市場真實頻率
    market_rate = rising_days / total_days if total_days > 0 else 0.0
    
    result = {
        'ticker': ticker,
        'total_days': total_days,
        'rising_days': rising_days,
        'market_rate': market_rate,
        'trigger_count': trigger_count,
        'success_count': success_count,
        'avg_confidence': avg_confidence,
        'precision': precision,
        'recall': recall,
        'decisions_df': decisions_df
    }
    
    return result


# =============================================================================
# 結果輸出
# =============================================================================
def save_summary_csv(results: list, output_dir: str):
    """儲存彙總 CSV"""
    summary_data = []
    
    for r in results:
        if r is None:
            continue
        summary_data.append({
            'Ticker': r['ticker'],
            '總天數': r['total_days'],
            '起漲天數': r['rising_days'],
            '市場起漲頻率': f"{r['market_rate']:.1%}",
            'Agent觸發次數': r['trigger_count'],
            '成功次數': r['success_count'],
            '平均信心度': f"{r['avg_confidence']:.3f}",
            '決策成功率(Precision)': f"{r['precision']:.1%}",
            '起漲點捕捉率(Recall)': f"{r['recall']:.1%}"
        })
    
    summary_df = pd.DataFrame(summary_data)
    csv_path = os.path.join(output_dir, "test_results_summary.csv")
    summary_df.to_csv(csv_path, index=False, encoding='utf-8-sig')
    print(f"\n✅ 彙總報表已儲存: {csv_path}")
    
    return summary_df


def plot_comparison_chart(results: list, output_dir: str):
    """繪製決策成功率 vs 市場真實頻率對比圖"""
    valid_results = [r for r in results if r is not None]
    
    if len(valid_results) == 0:
        print("⚠️ 無有效結果可繪圖")
        return
    
    tickers = [r['ticker'] for r in valid_results]
    precisions = [r['precision'] * 100 for r in valid_results]
    market_rates = [r['market_rate'] * 100 for r in valid_results]
    recalls = [r['recall'] * 100 for r in valid_results]
    
    x = np.arange(len(tickers))
    width = 0.25
    
    fig, ax = plt.subplots(figsize=(14, 7))
    
    bars1 = ax.bar(x - width, market_rates, width, label='市場起漲頻率', color='#2196F3', alpha=0.8)
    bars2 = ax.bar(x, precisions, width, label='決策成功率 (Precision)', color='#4CAF50', alpha=0.8)
    bars3 = ax.bar(x + width, recalls, width, label='捕捉率 (Recall)', color='#FF9800', alpha=0.8)
    
    ax.set_ylabel('百分比 (%)', fontsize=12)
    ax.set_xlabel('股票代碼', fontsize=12)
    ax.set_title(f'US Tech Stock Buy Agent 決策表現評估\n測試期間: {VAL_START} ~ {VAL_END}', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels(tickers, fontsize=11)
    ax.legend(loc='upper right', fontsize=10)
    ax.set_ylim(0, 100)
    ax.grid(axis='y', alpha=0.3)
    
    # 添加數值標籤
    def add_labels(bars):
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.1f}',
                        xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3),
                        textcoords="offset points",
                        ha='center', va='bottom', fontsize=8)
    
    add_labels(bars1)
    add_labels(bars2)
    add_labels(bars3)
    
    plt.tight_layout()
    
    chart_path = os.path.join(output_dir, "test_results_chart.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"✅ 對比圖表已儲存: {chart_path}")


def print_summary_table(results: list):
    """印出摘要表格"""
    print("\n" + "=" * 90)
    print("📊 Buy Agent 決策表現評估結果")
    print(f"   測試期間: {VAL_START} ~ {VAL_END}")
    print("=" * 90)
    
    print(f"\n{'Ticker':>8} | {'總天數':>6} | {'起漲天數':>8} | {'市場頻率':>8} | {'觸發次數':>8} | {'成功次數':>8} | {'Precision':>10} | {'Recall':>8}")
    print("-" * 90)
    
    total_rising = 0
    total_trigger = 0
    total_success = 0
    
    for r in results:
        if r is None:
            continue
        print(f"{r['ticker']:>8} | {r['total_days']:>6} | {r['rising_days']:>8} | {r['market_rate']:>7.1%} | {r['trigger_count']:>8} | {r['success_count']:>8} | {r['precision']:>9.1%} | {r['recall']:>7.1%}")
        total_rising += r['rising_days']
        total_trigger += r['trigger_count']
        total_success += r['success_count']
    
    print("-" * 90)
    
    # 總計
    overall_precision = total_success / total_trigger if total_trigger > 0 else 0
    overall_recall = total_success / total_rising if total_rising > 0 else 0
    
    print(f"{'總計':>8} | {'':>6} | {total_rising:>8} | {'':>8} | {total_trigger:>8} | {total_success:>8} | {overall_precision:>9.1%} | {overall_recall:>7.1%}")
    print("=" * 90)


# =============================================================================
# 主程式
# =============================================================================
def main():
    print("=" * 70)
    print("  US Tech Stock Buy Agent - 決策表現評估")
    print(f"  測試期間: {VAL_START} ~ {VAL_END}")
    print("=" * 70)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # =========================================================================
    # Step 1: 載入 Model Manifest
    # =========================================================================
    print("\n[Step 1] 載入 Model Manifest...")
    manifest = load_model_manifest(MODELS_PATH)
    
    if manifest is None:
        print("❌ 無法載入 manifest，終止測試")
        return
    
    print(f"  ✅ 已載入 {len(manifest['tickers'])} 個模型資訊")
    
    # =========================================================================
    # Step 2: 載入基準指數
    # =========================================================================
    print("\n[Step 2] 載入基準指數...")
    benchmark_df = load_or_update_local_csv(BENCHMARK)
    
    if benchmark_df is None:
        print("❌ 無法載入基準指數，終止測試")
        return
    
    # =========================================================================
    # Step 3: 逐股評估
    # =========================================================================
    print("\n[Step 3] 逐股評估...")
    results = []
    
    for ticker in TICKERS:
        print(f"\n📈 {ticker}")
        print("-" * 40)
        
        # 載入模型
        model = load_ticker_model(ticker, manifest)
        if model is None:
            results.append(None)
            continue
        print(f"  ✅ 模型載入成功")
        
        # 載入資料
        raw_df = load_or_update_local_csv(ticker)
        if raw_df is None:
            print(f"  ⚠️ {ticker} 資料載入失敗")
            results.append(None)
            continue
        
        # 計算特徵 (使用快取)
        features_df = calculate_features(raw_df, benchmark_df, ticker, use_cache=True)
        
        # 評估
        result = evaluate_ticker(ticker, model, features_df)
        results.append(result)
        
        if result:
            print(f"  📊 Precision: {result['precision']:.1%} | Recall: {result['recall']:.1%} | 信心度: {result['avg_confidence']:.3f}")
    
    # =========================================================================
    # Step 4: 輸出結果
    # =========================================================================
    print("\n[Step 4] 輸出結果...")
    
    # 印出摘要表格
    print_summary_table(results)
    
    # 儲存 CSV
    save_summary_csv(results, OUTPUT_DIR)
    
    # 繪製對比圖
    plot_comparison_chart(results, OUTPUT_DIR)
    
    print("\n" + "=" * 70)
    print("  ✅ 評估完成！")
    print(f"  📁 結果儲存於: {OUTPUT_DIR}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
