#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
US Tech Stock Buy Agent - 信心度分層分析 (Confidence Binning Analysis)
================================================================================
分析 Agent 在不同信心度區間的決策成功率，驗證模型校準度。

信心度區間:
- Tier 1: 90% ~ 100%
- Tier 2: 80% ~ 90%
- Tier 3: 70% ~ 80%
- Tier 4: 60% ~ 70%
- Tier 5: 50% ~ 60%

輸出:
- confidence_calibration_analysis.csv: 詳細分層統計
- confidence_calibration_chart.png: 分層對比圖表

作者：Phil Liang (Generated by Gemini)
日期：2026-01-18
================================================================================
"""

import os
import sys
import json
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from tqdm import tqdm

# Windows 終端機 UTF-8 編碼設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# 設定中文字型
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# 導入訓練腳本中的函數
from train_us_tech_buy_agent import (
    load_or_update_local_csv,
    calculate_features,
    TICKERS, BENCHMARK, FEATURE_COLS, VAL_RANGE, MODELS_PATH
)

from stable_baselines3 import PPO


# =============================================================================
# 常量定義
# =============================================================================
VAL_START, VAL_END = VAL_RANGE
OUTPUT_DIR = "test_results"

# 信心度區間定義
CONFIDENCE_BINS = [
    ("90-100%", 0.90, 1.00),
    ("80-90%", 0.80, 0.90),
    ("70-80%", 0.70, 0.80),
    ("60-70%", 0.60, 0.70),
    ("50-60%", 0.50, 0.60),
]


# =============================================================================
# 模型載入
# =============================================================================
def load_model_manifest(models_path: str) -> dict:
    """載入 model_manifest.json"""
    manifest_path = os.path.join(models_path, "model_manifest.json")
    
    if not os.path.exists(manifest_path):
        print(f"❌ 找不到 model_manifest.json: {manifest_path}")
        return None
    
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_ticker_model(ticker: str, manifest: dict) -> PPO:
    """載入指定 Ticker 的模型"""
    if ticker not in manifest.get("tickers", {}):
        print(f"  ⚠️ {ticker} 不在 manifest 中")
        return None
    
    model_path = manifest["tickers"][ticker]["model_path"]
    
    if not os.path.exists(model_path):
        print(f"  ⚠️ {ticker} 模型檔案不存在: {model_path}")
        return None
    
    try:
        model = PPO.load(model_path, device="cpu")
        return model
    except Exception as e:
        print(f"  ❌ {ticker} 模型載入失敗: {e}")
        return None


# =============================================================================
# 信心度分析
# =============================================================================
def get_action_confidence(model: PPO, obs: np.ndarray) -> tuple:
    """取得模型的動作與信心度"""
    obs_tensor = torch.as_tensor(obs.reshape(1, -1), dtype=torch.float32)
    
    with torch.no_grad():
        distribution = model.policy.get_distribution(obs_tensor)
        probs = distribution.distribution.probs.numpy()[0]
        action, _ = model.predict(obs, deterministic=True)
        action = int(action)
        buy_confidence = float(probs[1])
    
    return action, buy_confidence


def analyze_ticker_confidence(ticker: str, model: PPO, features_df: pd.DataFrame) -> list:
    """
    分析單一股票的信心度分層表現
    
    Returns:
        list: 各信心度區間的統計結果
    """
    # 過濾測試期間
    test_df = features_df[
        (features_df.index >= pd.Timestamp(VAL_START)) &
        (features_df.index <= pd.Timestamp(VAL_END))
    ].copy()
    
    test_df = test_df.dropna(subset=['Next_20d_Max'])
    
    if len(test_df) == 0:
        print(f"  ⚠️ {ticker} 無有效資料")
        return []
    
    print(f"  測試期間: {test_df.index[0].date()} ~ {test_df.index[-1].date()} ({len(test_df)} 天)")
    
    # 收集所有決策
    decisions = []
    
    for idx in tqdm(range(len(test_df)), desc=f"  Analyzing {ticker}", leave=False):
        row = test_df.iloc[idx]
        obs = row[FEATURE_COLS].values.astype(np.float32)
        action, buy_confidence = get_action_confidence(model, obs)
        next_20d_max = row['Next_20d_Max']
        is_success = next_20d_max >= 0.10
        
        # 只收集 Action=1 (BUY) 的決策
        if action == 1:
            decisions.append({
                'confidence': buy_confidence,
                'next_20d_max': next_20d_max,
                'is_success': is_success
            })
    
    if len(decisions) == 0:
        print(f"  ⚠️ {ticker} 無買入決策")
        return []
    
    decisions_df = pd.DataFrame(decisions)
    
    # 分層統計
    bin_results = []
    
    for bin_name, bin_low, bin_high in CONFIDENCE_BINS:
        bin_data = decisions_df[
            (decisions_df['confidence'] >= bin_low) & 
            (decisions_df['confidence'] < bin_high)
        ]
        
        signal_count = len(bin_data)
        success_count = bin_data['is_success'].sum() if signal_count > 0 else 0
        precision = success_count / signal_count if signal_count > 0 else 0.0
        avg_max_return = bin_data['next_20d_max'].mean() if signal_count > 0 else 0.0
        
        bin_results.append({
            'ticker': ticker,
            'confidence_bin': bin_name,
            'bin_low': bin_low,
            'bin_high': bin_high,
            'signal_count': signal_count,
            'success_count': success_count,
            'precision': precision,
            'avg_max_return': avg_max_return
        })
    
    # 額外統計整體 >50% 的情況
    total_signals = len(decisions_df)
    total_success = decisions_df['is_success'].sum()
    overall_precision = total_success / total_signals if total_signals > 0 else 0
    
    print(f"  📊 總買入信號: {total_signals} | 成功: {total_success} | 整體 Precision: {overall_precision:.1%}")
    
    return bin_results


# =============================================================================
# 結果輸出
# =============================================================================
def save_calibration_csv(all_results: list, output_dir: str) -> pd.DataFrame:
    """儲存分層分析 CSV"""
    if len(all_results) == 0:
        print("⚠️ 無結果可儲存")
        return None
    
    df = pd.DataFrame(all_results)
    df['precision_pct'] = df['precision'].apply(lambda x: f"{x:.1%}")
    df['avg_return_pct'] = df['avg_max_return'].apply(lambda x: f"{x:.1%}")
    
    csv_path = os.path.join(output_dir, "confidence_calibration_analysis.csv")
    df.to_csv(csv_path, index=False, encoding='utf-8-sig')
    print(f"\n✅ 分層分析已儲存: {csv_path}")
    
    return df


def plot_calibration_chart(all_results: list, output_dir: str):
    """繪製信心度校準圖表"""
    if len(all_results) == 0:
        print("⚠️ 無結果可繪圖")
        return
    
    df = pd.DataFrame(all_results)
    tickers = df['ticker'].unique()
    n_tickers = len(tickers)
    
    # 設定子圖布局
    n_cols = 5
    n_rows = (n_tickers + n_cols - 1) // n_cols
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 4 * n_rows))
    axes = axes.flatten() if n_rows > 1 else [axes] if n_tickers == 1 else axes.flatten()
    
    bin_labels = [b[0] for b in CONFIDENCE_BINS]
    x = np.arange(len(bin_labels))
    width = 0.6
    
    for i, ticker in enumerate(tickers):
        ax = axes[i]
        ticker_data = df[df['ticker'] == ticker].sort_values('bin_low', ascending=False)
        
        precisions = ticker_data['precision'].values * 100
        signal_counts = ticker_data['signal_count'].values
        
        # 長條圖：Precision
        bars = ax.bar(x, precisions, width, color='#4CAF50', alpha=0.8, label='Precision')
        
        # 折線圖：訊號次數 (右軸)
        ax2 = ax.twinx()
        line = ax2.plot(x, signal_counts, 'o-', color='#FF5722', linewidth=2, 
                        markersize=6, label='Signal Count')
        
        ax.set_ylabel('Precision (%)', fontsize=9)
        ax2.set_ylabel('Signal Count', fontsize=9, color='#FF5722')
        ax.set_xlabel('Confidence Bin', fontsize=9)
        ax.set_title(f'{ticker}', fontsize=11, fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels(bin_labels, fontsize=8, rotation=45)
        ax.set_ylim(0, 100)
        ax.grid(axis='y', alpha=0.3)
        
        # 添加數值標籤
        for bar, p, s in zip(bars, precisions, signal_counts):
            if s > 0:
                ax.annotate(f'{p:.0f}%', 
                            xy=(bar.get_x() + bar.get_width() / 2, bar.get_height()),
                            xytext=(0, 3), textcoords="offset points",
                            ha='center', va='bottom', fontsize=7)
    
    # 隱藏多餘的子圖
    for i in range(n_tickers, len(axes)):
        axes[i].set_visible(False)
    
    fig.suptitle(f'Buy Agent 信心度校準分析\n測試期間: {VAL_START} ~ {VAL_END}', 
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    
    chart_path = os.path.join(output_dir, "confidence_calibration_chart.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"✅ 校準圖表已儲存: {chart_path}")


def plot_aggregated_chart(all_results: list, output_dir: str):
    """繪製彙總校準圖表"""
    if len(all_results) == 0:
        return
    
    df = pd.DataFrame(all_results)
    
    # 按信心度區間彙總
    agg_df = df.groupby('confidence_bin').agg({
        'signal_count': 'sum',
        'success_count': 'sum',
        'avg_max_return': 'mean'
    }).reset_index()
    
    agg_df['precision'] = agg_df['success_count'] / agg_df['signal_count']
    
    # 按 bin_low 排序 (需要提取)
    bin_order = {b[0]: b[1] for b in CONFIDENCE_BINS}
    agg_df['bin_order'] = agg_df['confidence_bin'].map(bin_order)
    agg_df = agg_df.sort_values('bin_order', ascending=False)
    
    fig, ax = plt.subplots(figsize=(10, 6))
    
    x = np.arange(len(agg_df))
    width = 0.35
    
    bars1 = ax.bar(x - width/2, agg_df['precision'] * 100, width, 
                   label='Precision (%)', color='#4CAF50', alpha=0.8)
    bars2 = ax.bar(x + width/2, agg_df['avg_max_return'] * 100, width, 
                   label='Avg Max Return (%)', color='#2196F3', alpha=0.8)
    
    ax2 = ax.twinx()
    line = ax2.plot(x, agg_df['signal_count'], 's-', color='#FF5722', 
                    linewidth=2, markersize=8, label='Signal Count')
    
    ax.set_ylabel('百分比 (%)', fontsize=11)
    ax2.set_ylabel('訊號次數', fontsize=11, color='#FF5722')
    ax.set_xlabel('信心度區間', fontsize=11)
    ax.set_title(f'全體股票信心度校準分析 (彙總)\n測試期間: {VAL_START} ~ {VAL_END}', fontsize=13)
    ax.set_xticks(x)
    ax.set_xticklabels(agg_df['confidence_bin'].values, fontsize=10)
    ax.set_ylim(0, 80)
    ax.legend(loc='upper left')
    ax2.legend(loc='upper right')
    ax.grid(axis='y', alpha=0.3)
    
    # 添加數值標籤
    for bar in bars1:
        h = bar.get_height()
        ax.annotate(f'{h:.1f}%', xy=(bar.get_x() + bar.get_width() / 2, h),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontsize=9)
    
    for bar in bars2:
        h = bar.get_height()
        ax.annotate(f'{h:.1f}%', xy=(bar.get_x() + bar.get_width() / 2, h),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontsize=9)
    
    plt.tight_layout()
    
    chart_path = os.path.join(output_dir, "confidence_calibration_aggregated.png")
    plt.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"✅ 彙總圖表已儲存: {chart_path}")


def print_calibration_summary(all_results: list):
    """印出校準分析摘要"""
    if len(all_results) == 0:
        return
    
    df = pd.DataFrame(all_results)
    
    print("\n" + "=" * 100)
    print("📊 信心度分層分析摘要")
    print(f"   測試期間: {VAL_START} ~ {VAL_END}")
    print("=" * 100)
    
    # 按區間彙總
    print("\n【全體股票彙總】")
    print(f"{'信心度區間':>12} | {'訊號次數':>8} | {'成功次數':>8} | {'Precision':>10} | {'Avg Return':>10}")
    print("-" * 60)
    
    for bin_name, bin_low, bin_high in CONFIDENCE_BINS:
        bin_data = df[df['confidence_bin'] == bin_name]
        total_signals = bin_data['signal_count'].sum()
        total_success = bin_data['success_count'].sum()
        precision = total_success / total_signals if total_signals > 0 else 0
        avg_return = bin_data['avg_max_return'].mean() if len(bin_data) > 0 else 0
        
        print(f"{bin_name:>12} | {total_signals:>8} | {total_success:>8} | {precision:>9.1%} | {avg_return:>9.1%}")
    
    print("-" * 60)
    
    # 分析結論
    print("\n【關鍵發現】")
    
    # 找出黃金門檻
    for bin_name, bin_low, bin_high in CONFIDENCE_BINS:
        bin_data = df[df['confidence_bin'] == bin_name]
        if len(bin_data) > 0:
            avg_precision = (bin_data['success_count'].sum() / 
                           bin_data['signal_count'].sum() 
                           if bin_data['signal_count'].sum() > 0 else 0)
            if avg_precision >= 0.50:
                print(f"  ✅ 黃金門檻: 信心度 ≥ {bin_low:.0%} 時，整體 Precision 達 {avg_precision:.1%}")
                break
    
    # 高信心度樣本量
    high_conf_data = df[df['bin_low'] >= 0.80]
    high_conf_signals = high_conf_data['signal_count'].sum()
    total_signals = df['signal_count'].sum()
    high_conf_ratio = high_conf_signals / total_signals if total_signals > 0 else 0
    
    print(f"  📈 高信心度 (≥80%) 樣本量: {high_conf_signals} ({high_conf_ratio:.1%} of total)")
    
    if high_conf_ratio < 0.10:
        print(f"     ⚠️ 高信心度樣本較少，模型可能過於保守")
    elif high_conf_ratio > 0.50:
        print(f"     ✅ 高信心度樣本充足，模型信心度分佈良好")
    
    print("=" * 100)


# =============================================================================
# 主程式
# =============================================================================
def main():
    print("=" * 70)
    print("  US Tech Stock Buy Agent - 信心度分層分析")
    print(f"  測試期間: {VAL_START} ~ {VAL_END}")
    print("=" * 70)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 載入 manifest
    print("\n[Step 1] 載入 Model Manifest...")
    manifest = load_model_manifest(MODELS_PATH)
    if manifest is None:
        return
    
    # 載入基準指數
    print("\n[Step 2] 載入基準指數...")
    benchmark_df = load_or_update_local_csv(BENCHMARK)
    if benchmark_df is None:
        return
    
    # 逐股分析
    print("\n[Step 3] 信心度分層分析...")
    all_results = []
    
    for ticker in TICKERS:
        print(f"\n📈 {ticker}")
        print("-" * 40)
        
        model = load_ticker_model(ticker, manifest)
        if model is None:
            continue
        print(f"  ✅ 模型載入成功")
        
        raw_df = load_or_update_local_csv(ticker)
        if raw_df is None:
            continue
        
        features_df = calculate_features(raw_df, benchmark_df, ticker, use_cache=True)
        bin_results = analyze_ticker_confidence(ticker, model, features_df)
        all_results.extend(bin_results)
    
    # 輸出結果
    print("\n[Step 4] 輸出結果...")
    
    print_calibration_summary(all_results)
    save_calibration_csv(all_results, OUTPUT_DIR)
    plot_calibration_chart(all_results, OUTPUT_DIR)
    plot_aggregated_chart(all_results, OUTPUT_DIR)
    
    print("\n" + "=" * 70)
    print("  ✅ 分析完成！")
    print(f"  📁 結果儲存於: {OUTPUT_DIR}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
