#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
US Tech Stock Buy Agent Training Script
================================================================================
訓練 10 隻美股科技股的 Buy Agent，用於辨識「起漲點」。

階段訓練流程：
- Phase 1 (Pre-training): 整合 10 隻股票的歷史數據進行大規模預訓練
- Phase 2 (Fine-tuning): 針對每隻股票載入預訓練權重，進行個股微調

目標標的: NVDA, MSFT, AAPL, AMZN, META, AVGO, GOOGL, TSLA, NFLX, PLTR
基準指數: ^IXIC (Nasdaq Composite)

Buy Agent 目標: 預測未來 20 個交易日內，最高價報酬率是否達到 +10% 以上

作者：Phil Liang (Generated by Gemini)
日期：2026-01-18
================================================================================
"""

import os
import sys
import json
import glob
import shutil
import pickle
import multiprocessing
from datetime import datetime, date
from pathlib import Path

# Windows 終端機 UTF-8 編碼設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

import numpy as np
import pandas as pd
import yfinance as yf
import gymnasium as gym
from gymnasium import spaces
from ta.volatility import AverageTrueRange
from ta.momentum import RSIIndicator
from tqdm import tqdm

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import EvalCallback, CheckpointCallback, CallbackList
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv
from stable_baselines3.common.logger import configure
from stable_baselines3.common.utils import get_schedule_fn

import warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
warnings.filterwarnings('ignore')


# =============================================================================
# 常量定義
# =============================================================================
TICKERS = ["NVDA", "MSFT", "AAPL", "AMZN", "META", "AVGO", "GOOGL", "TSLA", "NFLX", "PLTR"]
BENCHMARK = "^IXIC"  # Nasdaq Composite

# 訓練/驗證期間 (與 train_v5_models.py 一致)
TRAIN_RANGES = [
    ("2000-01-01", "2017-10-15"),
    ("2023-10-16", "2025-12-31")
]
VAL_RANGE = ("2017-10-16", "2023-10-15")

WARMUP_DAYS = 250  # MA240 暖機期

# 訓練步數設定
PRETRAIN_BUY_STEPS = 1_000_000
FINETUNE_BUY_STEPS = 750_000

# 路徑設定
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(PROJECT_PATH, "data", "stocks")
CACHE_DIR = os.path.join(PROJECT_PATH, "data", "processed")
MODELS_PATH = os.path.join(PROJECT_PATH, "models_v5")

# 特徵列表 (移除 Volume 相關)
FEATURE_COLS = [
    'Norm_Close', 'Norm_Open', 'Norm_High', 'Norm_Low',
    'Norm_DC_Lower',
    'Norm_HA_Open', 'Norm_HA_High', 'Norm_HA_Low', 'Norm_HA_Close',
    'Norm_SuperTrend_1', 'Norm_SuperTrend_2',
    'Norm_RSI',
    # 'Norm_MFI',  # REMOVED - Volume 相關
    'Norm_ATR_Change',
    'Norm_RS_Ratio',
    'RS_ROC_5', 'RS_ROC_10', 'RS_ROC_20', 'RS_ROC_60', 'RS_ROC_120',
    'Feat_MA20_Slope',
    'Feat_Trend_Gap',
    'Feat_Bias_MA20',
    'Feat_Dist_MA60',
    'Feat_Dist_MA240',
    # 'Feat_Vol_Ratio',  # REMOVED - Volume 相關
    # 新增波動率代理
    'Feat_ATR_Ratio',    # ATR(5) / ATR(20)
    'Feat_HV20',         # 20日年化歷史波動率
    'Feat_Price_Pos',    # 20日價格區間百分比
    'Norm_K', 'Norm_D',
    'Norm_DIF', 'Norm_MACD', 'Norm_OSC',
]


# =============================================================================
# 1. 數據載入模組 (地端 CSV 增量更新)
# =============================================================================
def load_or_update_local_csv(ticker: str, start_date: str = "2000-01-01") -> pd.DataFrame:
    """
    載入本地 CSV 資料，若不存在或過期則從 Yahoo Finance 下載並更新
    
    Args:
        ticker: 股票代碼 (e.g., "NVDA", "^IXIC")
        start_date: 資料起始日期
    
    Returns:
        pd.DataFrame: 股價資料 (OHLCV)
    """
    os.makedirs(DATA_PATH, exist_ok=True)
    
    # 清理 ticker 名稱作為檔名
    safe_ticker = ticker.replace("^", "").replace(".", "_")
    csv_path = os.path.join(DATA_PATH, f"{safe_ticker}.csv")
    
    today = date.today()
    df = None
    need_update = True
    last_date = None
    
    # 1. 嘗試讀取現有 CSV
    if os.path.exists(csv_path):
        try:
            df = pd.read_csv(csv_path, parse_dates=['Date'], index_col='Date')
            last_date = df.index.max().date()
            
            # 檢查是否需要更新 (最近資料超過 1 天)
            days_diff = (today - last_date).days
            if days_diff <= 1:  # 週末可能 2 天，但我們放寬到 1 天
                need_update = False
                print(f"  ✅ {ticker} (Local, up to {last_date}): {len(df)} rows")
            else:
                print(f"  📥 {ticker} 需要更新 ({last_date} → {today})")
        except Exception as e:
            print(f"  ⚠️ {ticker} CSV 讀取錯誤: {e}")
            df = None
    else:
        print(f"  📥 {ticker} 首次下載...")
    
    # 2. 下載缺失的數據
    if need_update:
        try:
            if df is not None and last_date is not None:
                # 增量更新：只下載最後日期之後的資料
                download_start = (last_date + pd.Timedelta(days=1)).strftime('%Y-%m-%d')
            else:
                # 全新下載
                download_start = start_date
            
            new_data = yf.download(
                ticker, 
                start=download_start, 
                auto_adjust=True, 
                progress=False
            )
            
            if len(new_data) > 0:
                # 處理 MultiIndex columns (yfinance 有時會返回)
                if isinstance(new_data.columns, pd.MultiIndex):
                    new_data.columns = new_data.columns.get_level_values(0)
                
                new_data.index.name = 'Date'
                
                # 合併舊資料和新資料
                if df is not None:
                    df = pd.concat([df, new_data])
                    df = df[~df.index.duplicated(keep='last')]
                    df = df.sort_index()
                else:
                    df = new_data
                
                # 儲存到 CSV
                df.to_csv(csv_path)
                print(f"  ✅ {ticker} 更新完成: {len(df)} rows ({df.index[0].date()} ~ {df.index[-1].date()})")
            elif df is None:
                print(f"  ❌ {ticker} 無法下載任何資料")
                return None
        except Exception as e:
            print(f"  ❌ {ticker} 下載錯誤: {e}")
            if df is None:
                return None
    
    return df


def fetch_all_stock_data(start_date: str = "2000-01-01") -> dict:
    """
    下載/更新所有股票資料 (10 隻股票 + 基準指數)
    
    Returns:
        dict: {ticker: DataFrame}
    """
    print("=" * 60)
    print("📥 載入/更新 股票資料")
    print("=" * 60)
    
    all_data = {}
    
    # 1. 載入基準指數
    print(f"\n[基準指數] {BENCHMARK}")
    benchmark_df = load_or_update_local_csv(BENCHMARK, start_date)
    if benchmark_df is not None:
        all_data[BENCHMARK] = benchmark_df
    else:
        print(f"  ❌ 無法載入基準指數 {BENCHMARK}，終止程式")
        sys.exit(1)
    
    # 2. 載入個股
    print(f"\n[目標股票] {len(TICKERS)} 隻")
    for ticker in TICKERS:
        df = load_or_update_local_csv(ticker, start_date)
        if df is not None and len(df) > WARMUP_DAYS:
            all_data[ticker] = df
        else:
            print(f"  ⚠️ {ticker} 資料不足 (需要 > {WARMUP_DAYS} 天)")
    
    print(f"\n[Summary] 成功載入 {len(all_data)} 個標的")
    return all_data


# =============================================================================
# 2. 特徵工程
# =============================================================================
def calculate_heikin_ashi(df: pd.DataFrame) -> pd.DataFrame:
    """計算 Heikin Ashi K線"""
    ha_close = (df['Open'] + df['High'] + df['Low'] + df['Close']) / 4
    ha_open = [df['Open'].iloc[0]]
    for i in range(1, len(df)):
        ha_open.append((ha_open[-1] + ha_close.iloc[i-1]) / 2)
    ha_open = pd.Series(ha_open, index=df.index)
    return pd.DataFrame({
        'HA_open': ha_open,
        'HA_high': pd.concat([df['High'], ha_open, ha_close], axis=1).max(axis=1),
        'HA_low': pd.concat([df['Low'], ha_open, ha_close], axis=1).min(axis=1),
        'HA_close': ha_close
    })


def calculate_supertrend(df: pd.DataFrame, length: int = 14, multiplier: float = 3.0) -> pd.DataFrame:
    """計算 SuperTrend 指標"""
    atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=length).average_true_range()
    atr = atr.fillna(method='bfill')
    hl2 = (df['High'] + df['Low']) / 2
    basic_upper = hl2 + multiplier * atr
    basic_lower = hl2 - multiplier * atr
    
    final_upper = basic_upper.copy()
    final_lower = basic_lower.copy()
    trend = np.zeros(len(df))
    
    for i in range(1, len(df)):
        if basic_upper.iloc[i] < final_upper.iloc[i-1] or df['Close'].iloc[i-1] > final_upper.iloc[i-1]:
            final_upper.iloc[i] = basic_upper.iloc[i]
        else:
            final_upper.iloc[i] = final_upper.iloc[i-1]
            
        if basic_lower.iloc[i] > final_lower.iloc[i-1] or df['Close'].iloc[i-1] < final_lower.iloc[i-1]:
            final_lower.iloc[i] = basic_lower.iloc[i]
        else:
            final_lower.iloc[i] = final_lower.iloc[i-1]
        
        if df['Close'].iloc[i] > final_upper.iloc[i-1]:
            trend[i] = 1
        elif df['Close'].iloc[i] < final_lower.iloc[i-1]:
            trend[i] = -1
        else:
            trend[i] = trend[i-1]
    
    return pd.DataFrame({'SUPERT_': np.where(trend == 1, final_lower, final_upper)}, index=df.index)


def calculate_features(df_in: pd.DataFrame, benchmark_df: pd.DataFrame, 
                       ticker: str = "Unknown", use_cache: bool = True) -> pd.DataFrame:
    """
    計算特徵 (移除 Volume 相關，新增波動率代理)
    
    Args:
        df_in: 原始 OHLCV 資料
        benchmark_df: 基準指數資料 (^IXIC)
        ticker: 股票代碼
        use_cache: 是否使用快取
    
    Returns:
        pd.DataFrame: 包含所有特徵的 DataFrame
    """
    os.makedirs(CACHE_DIR, exist_ok=True)
    cache_path = os.path.join(CACHE_DIR, f"{ticker.replace('^', '_').replace('.', '_')}_features_ustech.pkl")
    
    if use_cache and os.path.exists(cache_path):
        try:
            with open(cache_path, 'rb') as f:
                cached_df = pickle.load(f)
            
            # 檢查快取是否涵蓋輸入數據的日期範圍
            input_last_date = df_in.index.max()
            cached_last_date = cached_df.index.max()
            
            if cached_last_date >= input_last_date:
                print(f"  [Cache] Loading features for {ticker} (up to {cached_last_date.strftime('%Y-%m-%d')})...")
                return cached_df
            else:
                print(f"  [Cache] Invalidating stale cache for {ticker}: {cached_last_date.strftime('%Y-%m-%d')} < {input_last_date.strftime('%Y-%m-%d')}")
        except Exception as e:
            print(f"  [Cache] Error loading cache for {ticker}: {e}")
    
    print(f"  [Compute] Generating features for {ticker}...")
    df = df_in.copy()
    
    # =========================================================================
    # 基礎技術指標
    # =========================================================================
    df['DC_Upper'] = df['High'].rolling(20).max().shift(1).fillna(method='bfill')
    df['DC_Lower'] = df['Low'].rolling(20).min().shift(1).fillna(method='bfill')
    df['DC_Upper_10'] = df['High'].rolling(10).max().shift(1).fillna(method='bfill')
    
    # ATR (多週期)
    df['ATR'] = AverageTrueRange(df['High'], df['Low'], df['Close'], window=10).average_true_range()
    df['ATR_5'] = AverageTrueRange(df['High'], df['Low'], df['Close'], window=5).average_true_range()
    df['ATR_20'] = AverageTrueRange(df['High'], df['Low'], df['Close'], window=20).average_true_range()
    
    # RSI (不使用 MFI，因為它依賴 Volume)
    df['RSI'] = RSIIndicator(df['Close'], window=14).rsi()
    
    # Heikin Ashi
    ha = calculate_heikin_ashi(df)
    df['HA_Open'] = ha['HA_open']
    df['HA_High'] = ha['HA_high']
    df['HA_Low'] = ha['HA_low']
    df['HA_Close'] = ha['HA_close']
    
    # SuperTrend
    df['SuperTrend_1'] = calculate_supertrend(df, 14, 2.0).iloc[:, 0]
    df['SuperTrend_2'] = calculate_supertrend(df, 21, 1.0).iloc[:, 0]
    
    # =========================================================================
    # 正規化 (使用 Donchian Channel 作為分母)
    # =========================================================================
    base_price = df['DC_Upper'].replace(0, np.nan).fillna(method='bfill')
    
    for col in ['Close', 'Open', 'High', 'Low', 'DC_Lower', 
                'HA_Open', 'HA_High', 'HA_Low', 'HA_Close', 
                'SuperTrend_1', 'SuperTrend_2']:
        df[f'Norm_{col}'] = df[col] / base_price
    
    df['Norm_RSI'] = df['RSI'] / 100.0
    df['Norm_ATR_Change'] = (df['ATR'] / df['ATR'].shift(1)).fillna(1.0)
    
    # =========================================================================
    # 均線與趨勢特徵
    # =========================================================================
    df['MA20'] = df['Close'].rolling(20).mean()
    df['MA60'] = df['Close'].rolling(60).mean()
    df['MA120'] = df['Close'].rolling(120).mean()
    df['MA240'] = df['Close'].rolling(240).mean()
    
    # (1) MA20 短期趨勢動能
    df['Feat_MA20_Slope'] = (df['MA20'] / df['MA20'].shift(1) - 1).fillna(0)
    
    # (2) MA20 vs MA240 市場體制
    df['Feat_Trend_Gap'] = ((df['MA20'] - df['MA240']) / df['MA240']).fillna(0)
    
    # (3) MA20 短期乖離
    df['Feat_Bias_MA20'] = ((df['Close'] - df['MA20']) / df['MA20']).fillna(0)
    
    # (4) MA60 季線支撐距離
    df['Feat_Dist_MA60'] = ((df['Close'] - df['MA60']) / df['MA60']).fillna(0)
    
    # (5) MA240 年線生命線位置
    df['Feat_Dist_MA240'] = ((df['Close'] - df['MA240']) / df['MA240']).fillna(0)
    
    # =========================================================================
    # 新增波動率代理指標 (替代 Volume)
    # =========================================================================
    # (1) ATR Ratio (5/20) - 偵測價格波動擴張
    df['Feat_ATR_Ratio'] = (df['ATR_5'] / (df['ATR_20'] + 1e-9)).fillna(1.0)
    
    # (2) 20日年化歷史波動率 (HV20)
    log_returns = np.log(df['Close'] / df['Close'].shift(1))
    df['Feat_HV20'] = log_returns.rolling(20).std() * np.sqrt(252)
    # 正規化到 0-1 範圍 (假設 HV 範圍 0-100%)
    df['Feat_HV20'] = (df['Feat_HV20'] / 1.0).clip(0, 1).fillna(0.3)
    
    # (3) 20日價格區間百分比 (Price_Pos)
    high_20 = df['High'].rolling(20).max()
    low_20 = df['Low'].rolling(20).min()
    df['Feat_Price_Pos'] = ((df['Close'] - low_20) / (high_20 - low_20 + 1e-9)).fillna(0.5)
    
    # =========================================================================
    # KD 與 MACD 特徵
    # =========================================================================
    # Stochastic KD (9, 3)
    low_min_9 = df['Low'].rolling(9).min()
    high_max_9 = df['High'].rolling(9).max()
    rsv = ((df['Close'] - low_min_9) / (high_max_9 - low_min_9 + 1e-9)) * 100
    df['K_raw'] = rsv.rolling(3).mean()
    df['D_raw'] = df['K_raw'].rolling(3).mean()
    df['Norm_K'] = (df['K_raw'] / 100.0).fillna(0.5)
    df['Norm_D'] = (df['D_raw'] / 100.0).fillna(0.5)
    
    # MACD (12, 26, 9)
    ema_12 = df['Close'].ewm(span=12, adjust=False).mean()
    ema_26 = df['Close'].ewm(span=26, adjust=False).mean()
    df['DIF'] = ema_12 - ema_26
    df['MACD_Signal'] = df['DIF'].ewm(span=9, adjust=False).mean()
    df['OSC'] = df['DIF'] - df['MACD_Signal']
    
    # 正規化：除以收盤價
    df['Norm_DIF'] = (df['DIF'] / df['Close']).fillna(0)
    df['Norm_MACD'] = (df['MACD_Signal'] / df['Close']).fillna(0)
    df['Norm_OSC'] = (df['OSC'] / df['Close']).fillna(0)
    
    # =========================================================================
    # 相對強度 (使用 ^IXIC 作為基準)
    # =========================================================================
    if benchmark_df is not None:
        bench_close = benchmark_df['Close'].reindex(df.index).fillna(method='ffill')
        df['RS_Raw'] = df['Close'] / bench_close
        rs_min = df['RS_Raw'].rolling(250).min()
        rs_max = df['RS_Raw'].rolling(250).max()
        df['Norm_RS_Ratio'] = ((df['RS_Raw'] - rs_min) / ((rs_max - rs_min).replace(0, np.nan).fillna(1.0) + 1e-9)).fillna(0.5)
        
        for period in [5, 10, 20, 60, 120]:
            df[f'RS_ROC_{period}'] = df['RS_Raw'].pct_change(period).fillna(0)
    else:
        df['Norm_RS_Ratio'] = 0.5
        for period in [5, 10, 20, 60, 120]:
            df[f'RS_ROC_{period}'] = 0.0
    
    # =========================================================================
    # 目標標籤 (20 天最高價報酬率)
    # =========================================================================
    df['Signal_Buy_Filter'] = df['High'] > df['DC_Upper_10']
    
    # Next_20d_Max: 未來 20 交易日內的最高價報酬率
    df['Next_20d_Max'] = df['High'].shift(-1).iloc[::-1].rolling(20, min_periods=20).max().iloc[::-1] / df['Close'] - 1
    
    # =========================================================================
    # 移除 NaN
    # =========================================================================
    # 移除因 MA240 造成的前 250 天空值
    df = df.dropna(subset=['MA240'])
    # 移除其餘 NaN (排除目標欄位)
    feature_cols_check = [c for c in FEATURE_COLS if c in df.columns]
    df = df.dropna(subset=feature_cols_check)
    
    # =========================================================================
    # 快取
    # =========================================================================
    if use_cache:
        try:
            with open(cache_path, 'wb') as f:
                pickle.dump(df, f)
        except:
            pass
    
    return df


# =============================================================================
# 3. RL 環境定義
# =============================================================================
class BuyEnvHybridV5US(gym.Env):
    """
    Buy Agent 環境 - 美股科技股版本
    
    目標: 預測未來 20 天內最高價報酬率 >= 10%
    獎勵結構 (對稱):
    - 買對 (action=1, 漲幅≥10%): +1.0
    - 買錯 (action=1, 漲幅<10%): 0.0
    - 錯過 (action=0, 漲幅≥10%): 0.0
    - 正確迴避 (action=0, 漲幅<10%): +1.0
    """
    
    def __init__(self, data_dict: dict, is_training: bool = True, balance_tickers: bool = False):
        """
        Args:
            data_dict: {ticker: DataFrame} 包含特徵的資料
            is_training: 是否為訓練模式 (影響抽樣方式)
            balance_tickers: 是否平衡各 Ticker 的抽樣機率 (預訓練時應為 True)
        """
        super().__init__()
        
        self.is_training = is_training
        self.balance_tickers = balance_tickers
        
        # 儲存樣本
        self.samples = []           # 所有樣本
        self.pos_samples = []       # 正樣本 (>= 10%)
        self.neg_samples = []       # 負樣本 (< 10%)
        self.ticker_samples = {}    # 依 Ticker 分組的樣本
        
        for ticker, df in data_dict.items():
            df = df.dropna(subset=['Next_20d_Max'])
            
            if len(df) == 0:
                continue
            
            states = df[FEATURE_COLS].values.astype(np.float32)
            future_rets = df['Next_20d_Max'].values.astype(np.float32)
            
            ticker_pos = []
            ticker_neg = []
            
            for i in range(len(df)):
                sample = (states[i], future_rets[i], ticker)
                self.samples.append(sample)
                
                if future_rets[i] >= 0.10:
                    self.pos_samples.append(sample)
                    ticker_pos.append(sample)
                else:
                    self.neg_samples.append(sample)
                    ticker_neg.append(sample)
            
            self.ticker_samples[ticker] = {'pos': ticker_pos, 'neg': ticker_neg}
        
        print(f"[BuyEnvV5US] Total: {len(self.samples)} | Pos (≥10%): {len(self.pos_samples)} | Neg: {len(self.neg_samples)}")
        print(f"             Tickers: {list(self.ticker_samples.keys())}")
        
        self.action_space = spaces.Discrete(2)
        self.observation_space = spaces.Box(-np.inf, np.inf, shape=(len(FEATURE_COLS),), dtype=np.float32)
        self.current_sample = None
    
    def reset(self, seed=None, options=None):
        if self.is_training:
            if self.balance_tickers and self.ticker_samples:
                # 預訓練模式：先隨機選 Ticker，再 50/50 類別平衡
                ticker = np.random.choice(list(self.ticker_samples.keys()))
                ticker_data = self.ticker_samples[ticker]
                
                if np.random.rand() < 0.5 and ticker_data['pos']:
                    self.current_sample = ticker_data['pos'][np.random.randint(len(ticker_data['pos']))]
                elif ticker_data['neg']:
                    self.current_sample = ticker_data['neg'][np.random.randint(len(ticker_data['neg']))]
                else:
                    self.current_sample = self.samples[np.random.randint(len(self.samples))]
            else:
                # 微調模式：50/50 類別平衡
                if np.random.rand() < 0.5 and self.pos_samples:
                    self.current_sample = self.pos_samples[np.random.randint(len(self.pos_samples))]
                elif self.neg_samples:
                    self.current_sample = self.neg_samples[np.random.randint(len(self.neg_samples))]
                else:
                    self.current_sample = self.samples[np.random.randint(len(self.samples))]
        else:
            # 驗證模式：使用真實分佈
            self.current_sample = self.samples[np.random.randint(len(self.samples))]
        
        return self.current_sample[0], {}
    
    def step(self, action):
        _, max_ret, _ = self.current_sample
        is_success = max_ret >= 0.10  # 20 天內最高達 +10%
        
        # 對稱獎勵結構
        if action == 1:  # BUY
            reward = 1.0 if is_success else 0.0
        else:  # WAIT
            reward = 0.0 if is_success else 1.0
        
        return self.current_sample[0], reward, True, False, {}


# =============================================================================
# 4. 輔助函式
# =============================================================================
def filter_by_ranges(df: pd.DataFrame, ranges: list) -> pd.DataFrame:
    """根據日期範圍列表過濾 DataFrame"""
    mask = pd.Series(False, index=df.index)
    for start, end in ranges:
        mask |= (df.index >= pd.Timestamp(start)) & (df.index <= pd.Timestamp(end))
    return df[mask]


def get_valid_train_ranges(ticker: str, df: pd.DataFrame, train_ranges: list) -> list:
    """
    取得有效的訓練區間 (排除股票尚未上市或暖機期不足的部分)
    
    Args:
        ticker: 股票代碼
        df: 原始資料
        train_ranges: 預設訓練區間列表
    
    Returns:
        list: 有效的訓練區間列表
    """
    if len(df) == 0:
        return []
    
    first_valid_date = df.index[0] + pd.Timedelta(days=WARMUP_DAYS)
    
    valid_ranges = []
    for start, end in train_ranges:
        start_dt = pd.Timestamp(start)
        end_dt = pd.Timestamp(end)
        
        if end_dt < first_valid_date:
            continue  # 整個區間無效
        
        actual_start = max(start_dt, first_valid_date)
        if actual_start < end_dt:
            valid_ranges.append((actual_start.strftime('%Y-%m-%d'), end))
    
    if len(valid_ranges) < len(train_ranges):
        print(f"  ⚠️ {ticker}: 部分訓練區間無效 (上市日期晚或暖機期不足)")
    
    return valid_ranges


def clear_cache():
    """清除特徵快取"""
    print("\n[Cache] Clearing feature cache...")
    if os.path.exists(CACHE_DIR):
        pkl_files = glob.glob(os.path.join(CACHE_DIR, "*_ustech.pkl"))
        for f in pkl_files:
            try:
                os.remove(f)
                print(f"  Deleted: {os.path.basename(f)}")
            except Exception as e:
                print(f"  Failed: {os.path.basename(f)} - {e}")


# =============================================================================
# 5. 訓練流程
# =============================================================================
def run_pretraining(train_data: dict, models_path: str):
    """
    Phase 1: Pre-training on combined 10-stock data
    
    Args:
        train_data: {ticker: DataFrame} 訓練資料
        models_path: 模型儲存路徑
    """
    print("\n" + "=" * 60)
    print("Phase 1: Pre-training (Combined 10 US Tech Stocks)")
    print("=" * 60)
    print(f"  Steps: {PRETRAIN_BUY_STEPS:,}")
    print(f"  Tickers: {list(train_data.keys())}")
    print(f"  Output: {models_path}")
    print("=" * 60)
    
    os.makedirs(models_path, exist_ok=True)
    os.makedirs(os.path.join(models_path, "best_pretrain"), exist_ok=True)
    
    tensorboard_log = "./tensorboard_logs/"
    os.makedirs(tensorboard_log, exist_ok=True)
    
    n_envs = min(8, max(1, multiprocessing.cpu_count() - 1))
    print(f"[System] CPU cores: {multiprocessing.cpu_count()}, Using {n_envs} envs")
    
    ppo_params = {
        "learning_rate": 0.0001,
        "n_steps": max(128, 2048 // n_envs),
        "batch_size": 512,
        "ent_coef": 0.01,
        "device": "cpu",
        "policy_kwargs": dict(net_arch=[64, 64, 64]),
        "verbose": 1,
        "tensorboard_log": tensorboard_log
    }
    
    # 建立訓練環境 (balance_tickers=True 確保各 Ticker 抽樣均等)
    print("\n🛒 Training Buy Agent (Pre-training on all tickers)...")
    buy_env = make_vec_env(
        BuyEnvHybridV5US, n_envs=n_envs, vec_env_cls=SubprocVecEnv,
        env_kwargs={'data_dict': train_data, 'is_training': True, 'balance_tickers': True}
    )
    
    # 建立評估環境
    eval_buy_env = make_vec_env(
        BuyEnvHybridV5US, n_envs=1, vec_env_cls=DummyVecEnv,
        env_kwargs={'data_dict': train_data, 'is_training': False, 'balance_tickers': False}
    )
    
    buy_model = PPO("MlpPolicy", buy_env, **ppo_params)
    
    # Callbacks
    buy_callbacks = CallbackList([
        CheckpointCallback(save_freq=100000, save_path=models_path, name_prefix="ppo_buy_base_ustech"),
        EvalCallback(eval_buy_env, 
                     best_model_save_path=os.path.join(models_path, "best_pretrain"),
                     log_path="./logs/", eval_freq=20000, n_eval_episodes=100, 
                     deterministic=True)
    ])
    
    buy_model.learn(total_timesteps=PRETRAIN_BUY_STEPS, callback=buy_callbacks, 
                    tb_log_name="buy_pretrain_us_tech")
    
    # 複製 best model
    best_buy_path = os.path.join(models_path, "best_pretrain", "best_model.zip")
    buy_base_path = os.path.join(models_path, "ppo_buy_base_us_tech.zip")
    if os.path.exists(best_buy_path):
        shutil.copy(best_buy_path, buy_base_path)
        print(f"[Pre-train] ✅ Buy Agent: Copied BEST model to {buy_base_path}")
    else:
        buy_model.save(buy_base_path.replace('.zip', ''))
        print(f"[Pre-train] ⚠️ Buy Agent: Best model not found, saved last step model")
    
    buy_env.close()
    eval_buy_env.close()
    
    print("[System] Pre-training Completed.")


def run_finetuning(ticker: str, ticker_train_data: dict, ticker_eval_data: dict, 
                   models_path: str, manifest: dict):
    """
    Phase 2: Fine-tuning for individual ticker
    
    Args:
        ticker: 股票代碼
        ticker_train_data: {ticker: DataFrame} 該股票的訓練資料
        ticker_eval_data: {ticker: DataFrame} 該股票的驗證資料
        models_path: 模型儲存路徑
        manifest: 模型清單字典 (會被更新)
    """
    print(f"\n[Fine-tune] {ticker}")
    print("-" * 40)
    
    ticker_model_dir = os.path.join(models_path, "finetuned", ticker)
    os.makedirs(ticker_model_dir, exist_ok=True)
    os.makedirs(os.path.join(ticker_model_dir, "best"), exist_ok=True)
    
    tensorboard_log = "./tensorboard_logs/"
    
    # 載入預訓練權重
    buy_base_path = os.path.join(models_path, "ppo_buy_base_us_tech.zip")
    if not os.path.exists(buy_base_path):
        print(f"  ❌ Base model not found: {buy_base_path}")
        return
    
    n_envs = min(4, max(1, multiprocessing.cpu_count() - 1))
    
    # 建立環境
    buy_env = make_vec_env(
        BuyEnvHybridV5US, n_envs=n_envs, vec_env_cls=SubprocVecEnv,
        env_kwargs={'data_dict': ticker_train_data, 'is_training': True, 'balance_tickers': False}
    )
    
    eval_env = make_vec_env(
        BuyEnvHybridV5US, n_envs=1, vec_env_cls=DummyVecEnv,
        env_kwargs={'data_dict': ticker_eval_data, 'is_training': False}
    )
    
    # 載入模型並調整超參數
    buy_model = PPO.load(buy_base_path, env=buy_env, device="cpu")
    
    # Fine-tune 超參數 (LR = pretrain 的 1/10)
    buy_model.learning_rate = 1e-5
    buy_model.lr_schedule = get_schedule_fn(buy_model.learning_rate)
    buy_model.ent_coef = 0.01
    
    # 獨立 TensorBoard 日誌
    log_name = f"buy_finetune_{ticker}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    logger = configure(os.path.join(tensorboard_log, log_name), ["tensorboard", "stdout"])
    buy_model.set_logger(logger)
    
    # Callbacks
    callbacks = CallbackList([
        CheckpointCallback(save_freq=100000, save_path=ticker_model_dir, name_prefix=f"ppo_buy_{ticker}"),
        EvalCallback(eval_env, 
                     best_model_save_path=os.path.join(ticker_model_dir, "best"),
                     log_path=os.path.join(ticker_model_dir, "logs"),
                     eval_freq=10000, n_eval_episodes=100, deterministic=True)
    ])
    
    print(f"  Training {FINETUNE_BUY_STEPS:,} steps (LR: 1e-5)...")
    buy_model.learn(total_timesteps=FINETUNE_BUY_STEPS, callback=callbacks, reset_num_timesteps=False)
    
    # 儲存最終模型
    final_path = os.path.join(ticker_model_dir, f"ppo_buy_{ticker}_final.zip")
    best_path = os.path.join(ticker_model_dir, "best", "best_model.zip")
    
    if os.path.exists(best_path):
        shutil.copy(best_path, final_path)
        print(f"  ✅ Copied BEST model to {final_path}")
    else:
        buy_model.save(final_path.replace('.zip', ''))
        print(f"  ⚠️ Best model not found, saved last step model")
    
    # 更新 manifest
    train_df = ticker_train_data[ticker]
    eval_df = ticker_eval_data[ticker]
    
    # 計算驗證集勝率 (簡化版)
    eval_samples = eval_df.dropna(subset=['Next_20d_Max'])
    if len(eval_samples) > 0:
        pos_ratio = (eval_samples['Next_20d_Max'] >= 0.10).mean()
    else:
        pos_ratio = 0.0
    
    manifest["tickers"][ticker] = {
        "model_path": final_path,
        "train_end_date": train_df.index[-1].strftime('%Y-%m-%d'),
        "val_win_rate": round(pos_ratio, 3),
        "actual_training_days": len(train_df),
        "base_model_version": "ppo_buy_base_us_tech"
    }
    
    buy_env.close()
    eval_env.close()
    
    print(f"  ✅ {ticker} Fine-tuning Complete (Train days: {len(train_df)})")


def run_all_finetuning(all_train_data: dict, all_eval_data: dict, models_path: str):
    """
    對所有股票執行 Fine-tuning
    """
    print("\n" + "=" * 60)
    print("Phase 2: Fine-tuning (Individual Tickers)")
    print("=" * 60)
    print(f"  Steps per ticker: {FINETUNE_BUY_STEPS:,}")
    print(f"  Tickers: {list(all_train_data.keys())}")
    print("=" * 60)
    
    manifest = {
        "version": "v5_us_tech",
        "base_model": "ppo_buy_base_us_tech.zip",
        "created_at": datetime.now().isoformat(),
        "tickers": {}
    }
    
    for ticker in all_train_data.keys():
        if ticker == BENCHMARK:
            continue  # 跳過基準指數
        
        ticker_train = {ticker: all_train_data[ticker]}
        ticker_eval = {ticker: all_eval_data.get(ticker, all_train_data[ticker])}
        
        run_finetuning(ticker, ticker_train, ticker_eval, models_path, manifest)
    
    # 儲存 manifest
    manifest_path = os.path.join(models_path, "model_manifest.json")
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    
    print(f"\n[System] Model manifest saved to: {manifest_path}")
    print("[System] Fine-tuning Completed for all tickers.")


# =============================================================================
# 6. 主程式
# =============================================================================
def main():
    print("=" * 70)
    print("  US Tech Stock Buy Agent Training Script")
    print("  目標標的: " + ", ".join(TICKERS))
    print("  基準指數: " + BENCHMARK)
    print("=" * 70)
    
    # =========================================================================
    # Step 1: 載入資料
    # =========================================================================
    raw_data = fetch_all_stock_data()
    benchmark_df = raw_data.get(BENCHMARK)
    
    # =========================================================================
    # Step 2: 計算特徵
    # =========================================================================
    print("\n" + "=" * 60)
    print("📊 計算特徵")
    print("=" * 60)
    
    all_features = {}
    for ticker, df in raw_data.items():
        try:
            processed = calculate_features(df, benchmark_df, ticker, use_cache=True)
            if len(processed) > 100:
                all_features[ticker] = processed
                print(f"  ✅ {ticker}: {len(processed)} rows")
        except Exception as e:
            print(f"  ❌ {ticker}: {e}")
    
    # =========================================================================
    # Step 3: 分割訓練/驗證集
    # =========================================================================
    print("\n" + "=" * 60)
    print("📂 分割訓練/驗證集")
    print("=" * 60)
    
    train_data = {}
    eval_data = {}
    
    val_start, val_end = VAL_RANGE
    
    for ticker, df in all_features.items():
        if ticker == BENCHMARK:
            continue
        
        # 取得有效的訓練區間
        valid_ranges = get_valid_train_ranges(ticker, raw_data[ticker], TRAIN_RANGES)
        
        if not valid_ranges:
            print(f"  ⚠️ {ticker}: 無有效訓練區間，跳過")
            continue
        
        # 過濾訓練資料
        train_df = filter_by_ranges(df, valid_ranges)
        
        # 驗證資料
        eval_df = df[(df.index >= pd.Timestamp(val_start)) & (df.index <= pd.Timestamp(val_end))]
        
        if len(train_df) > 100:
            train_data[ticker] = train_df
            eval_data[ticker] = eval_df if len(eval_df) > 50 else train_df
            print(f"  ✅ {ticker}: Train {len(train_df)} | Eval {len(eval_df)}")
        else:
            print(f"  ⚠️ {ticker}: 訓練資料不足 ({len(train_df)} rows)")
    
    print(f"\n[Summary] 有效標的: {len(train_data)} / {len(TICKERS)}")
    
    # =========================================================================
    # Step 4: Pre-training
    # =========================================================================
    buy_base_path = os.path.join(MODELS_PATH, "ppo_buy_base_us_tech.zip")
    
    if os.path.exists(buy_base_path):
        print("\n" + "=" * 60)
        print("[Skip] Pre-training (Base model exists)")
        print(f"       {buy_base_path}")
        print("=" * 60)
    else:
        run_pretraining(train_data, MODELS_PATH)
    
    # =========================================================================
    # Step 5: Fine-tuning
    # =========================================================================
    run_all_finetuning(train_data, eval_data, MODELS_PATH)
    
    # =========================================================================
    # 完成
    # =========================================================================
    print("\n" + "=" * 70)
    print("  ✅ 訓練完成！")
    print("=" * 70)
    print(f"""
📁 模型儲存位置:
   {MODELS_PATH}/ppo_buy_base_us_tech.zip (Base Model)
   {MODELS_PATH}/finetuned/{{TICKER}}/ppo_buy_{{TICKER}}_final.zip

📊 模型清單:
   {MODELS_PATH}/model_manifest.json

📈 TensorBoard 監控:
   tensorboard --logdir ./tensorboard_logs/
""")


if __name__ == "__main__":
    main()
